### ISSUE TITLE
[Improvement?] Gentoo ebuild

### ISSUE THREAD

**Issue by Wa1t5** [hyprwm/xdg-desktop-portal-hyprland#10]
I modified the xdpw ebuild and added  the necessary dependencies and install options to make it work with xdph.

Overlay: https://github.com/Wa1t5/useless-overlay/blob/main/gui-libs/xdg-desktop-portal-hyprland/xdg-desktop-portal-hyprland-9999.ebuild

**Comment by vaxerski** [comment]
umm, cool, you can add a link to it to the hyprland wiki in the xdph page.
