### ISSUE TITLE
Not always start on boot

### ISSUE THREAD

**Issue by coffebar** [hyprwm/xdg-desktop-portal-hyprland#104]
This kinda workflow is "working" for me from one to another system update for like last month or two.  And it is very annoying.
Need help to localize this bug or work around it. Please advise where to start.

### How I reboot my computer:

1. `systemctl reboot`
2. shutdown correctly
3. boot into Hyprland ( [config](https://github.com/coffebar/dotfiles/blob/master/.config/hyprland/hyprland.conf) )
This script starts from exec-once:
```bash
#!/bin/bash
sleep 1
killall -e xdg-desktop-portal-hyprland
killall -e xdg-desktop-portal-wlr
killall xdg-desktop-portal
/usr/lib/xdg-desktop-portal-hyprland &
sleep 2
/usr/lib/xdg-desktop-portal &
```
Desktop portal is not started (gtk apps long load, firefox crashes, volume indicator missing) 

4. exit hyprland - computer hung, black screen, cooler is working hard
5. wait for 10 minutes, and do a hard shutdown by holding the Power key.
6. boot into Hyprland and everything works, desktop portal is working.

Sometimes it takes 2-3 reboots.

**Comment by coffebar** [comment]
It was 10 minutes earlier, then I rebooted several times in a row and it does not reproduce now. 
Please don't close, the problem is relevant anyways

**Comment by thejch** [comment]
Have you tried logging the output
`/usr/lib/xdg-desktop-portal-hyprland &> logfile`

**Comment by Fuchskaute** [comment]
That scripts looks like it was taken straight from the Gentoo Wiki. Using a script like that to start xdph/other desktop portals is not necessary on systemd, they will automatically be started as part of your dbus user session. Are you starting Hyprland with `dbus-run-session` too? 

I do not have any such scripts in my hyprland config and `systemctl --user status xdg-desktop-portal` (or any specific portal) gives me a positive output and it works just finne.

**Comment by coffebar** [comment]
@Fuchskaute
The script was taken straight from [hyprland wiki](https://wiki.hyprland.org/Useful-Utilities/Hyprland-desktop-portal/)
Tested without it and it did not work. The script is required for me, or need to do some more configuration.

I believe the described problem is related to the timing of this script. Sleep 1-2 seems not reliable values.

> pacman -Q | awk '{print $1}' | grep '^xdg-'

```
xdg-dbus-proxy
xdg-desktop-portal
xdg-desktop-portal-hyprland-git
xdg-user-dirs
xdg-utils
```
is it the correct set of programs?

@thejch Unfortunately, logging gives nothing - empty log
Only this thing spamming from xdg-desktop-portal every time
`(/usr/lib/xdg-desktop-portal:3025): xdg-desktop-portal-WARNING **: 11:08:56.042: No skeleton to export`

**Comment by Fuchskaute** [comment]
I apologize in that case, that seems rather interesting..

**Comment by kaii-lb** [comment]
same issue here, and now flatpak apps all report
`(com.github.tchx84.Flatseal:2): Gdk-WARNING **: 18:07:55.873: Failed to read portal settings: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop`

which is annoying as hell (i use left aligned window controls)

**Comment by NgoHuy** [comment]
I have same issue, but no working, it related to #114 , xdgh crashed
![image](https://github.com/hyprwm/xdg-desktop-portal-hyprland/assets/1238112/40e46a6e-90f6-4971-9312-f613d72517f7)

**Comment by jones-sam** [comment]
I know this isn't a "real" solution, but I fixed this issue (at least for now) just by switching from `xdg-desktop-portal-hyprland-git` to `xdg-desktop-portal-hyprland`

**Comment by coffebar** [comment]
> I know this isn't a "real" solution, but I fixed this issue (at least for now) just by switching from `xdg-desktop-portal-hyprland-git` to `xdg-desktop-portal-hyprland`

You know, it will work till next update of the `xdg-desktop-portal-hyprland`

**Comment by BrayanLope5** [comment]
Having the same issue and I am on `xdg-desktop-portal-hyprland`, not `xdg-desktop-portal-hyprland-git`.

**Comment by Nambers** [comment]
> Unfortunately, logging gives nothing - empty log Only this thing spamming from xdg-desktop-portal every time `(/usr/lib/xdg-desktop-portal:3025): xdg-desktop-portal-WARNING **: 11:08:56.042: No skeleton to export`

I also had this issue
versions(I also tried `xdg-desktop-portal-hyprland-git`):
```
> pacman -Q xdg-desktop-portal
xdg-desktop-portal 1.18.4-1
> pacman -Q xdg-desktop-portal-hyprland
xdg-desktop-portal-hyprland 1.3.1-6
```
And I do have `exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP` in my `hyprland.conf`. This happened when I try to manually run `xdg-desktop-portal-hyprland` and `xdg-desktop-portal`(which didn't automatically start at boot and I'm not sure what are their normal behaviors). I'm concern about these are the reason for my OBS said `info: [pipewire] No captures available`.

**Comment by thyeun** [comment]
I still getting inactive status, as can see from the below image. It is consider normal?

![240729_17h50m24s_screenshot](https://github.com/user-attachments/assets/3fe306e8-624a-458b-a410-ee8a95dedd5f)

**Comment by Nambers** [comment]
> I still getting inactive status, as can see from the below image. It is consider normal?
> 

In my case, rn `xdg-desktop-portal-hyprland` is inactive but I had `xdg-desktop-portal-gtk` active. idk if this behavior normal but OBS screen recording works. And when I uninstall `xdg-desktop-portal-gtk`, `xdg-desktop-protal` will throw `xdg-desktop-por[24192]: No skeleton to export`

**Comment by coffebar** [comment]
It's weird, I checked my `xdg-desktop-portal-hyprland` and it has failed status

> xdg-desktop-portal-hyprland.service - Portal service (Hyprland implementation)
>      Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal-hyprland.service; static)
>      Active: failed (Result: exit-code) since Mon 2024-07-29 12:01:00 WEST; 3min 51s ago
>    Duration: 4ms
>  Invocation: 9bb60c47ba2d400cb07066bb38363a54
>     Process: 5637 ExecStart=/usr/lib/xdg-desktop-portal-hyprland (code=exited, status=1/FAILURE)
>    Main PID: 5637 (code=exited, status=1/FAILURE) 
```

Jul 29 12:01:00 crab xdg-desktop-portal-hyprland[5637]: [LOG] Initializing xdph...
Jul 29 12:01:00 crab xdg-desktop-portal-hyprland[5637]: [CRITICAL] Couldn't create the dbus connection ([org.freedesktop.DBus.Error.FileExists] Failed to request bus name (File exists))
Jul 29 12:01:00 crab systemd[1260]: xdg-desktop-portal-hyprland.service: Main process exited, code=exited, status=1/FAILURE

```
I don't have any other portals in my system installed. 
In my case, xdg-desktop-portal-hyprland is installed from AUR, but hyprland is build from source from git.

**Comment by coffebar** [comment]
Oh, I have started `xdg-desktop-portal-hyprland` manually from hyprland.conf so service can't run, because program is allready running. So it's expected

**Comment by Natzukashi** [comment]
2 years later and I am having the same issue. `xdg-desktop-portal-hyprland` doesn't autostart, even though `xdg-desktop-portal` does.

**Comment by coffebar** [comment]
@Natzukashi , probably there is something should be fixed on your end. Check you have up-to-date versions of xdg-desktop-portal-hyprland and hyprland, check logs and review the documentation at https://wiki.hypr.land/Hypr-Ecosystem/xdg-desktop-portal-hyprland/

**Comment by Natzukashi** [comment]
@coffebar actually its been fixed now and the issue was completely different. It was my network module not responding quickly enough for waybar and caused waybar to wait for it to start up...

If you don't get my explaination, well even I don't really know what was wrong... though I can confirm it wasn't `xdg-desktop-portal-hyprland`
