### ISSUE TITLE
Share picker scaled wrong on upright display

### ISSUE THREAD

**Issue by galister** [hyprwm/xdg-desktop-portal-hyprland#105]
Not sure if this should go under this repo or Hyprland.

Share picker seems to not respect the scaling setting, but instead rely on the screen dimensions for the font size.

`hyprland.conf`:

```
monitor=HDMI-A-1, preferred, 0x0, 1, transform, 1
```

![image](https://github.com/hyprwm/xdg-desktop-portal-hyprland/assets/22305755/fdd2e383-a258-4ccf-865a-e6e8e39097ea)

With `transform, 1` removed:
![image](https://github.com/hyprwm/xdg-desktop-portal-hyprland/assets/22305755/cf0839ce-7b29-4b08-b6af-b74f9365f45b)

**Comment by vaxerski** [comment]
wouldn't that be a qt bug?
