### ISSUE TITLE
wrong color on obs

### ISSUE THREAD

**Issue by glepnir** [hyprwm/xdg-desktop-portal-hyprland#106]
relate issue https://github.com/obsproject/obs-studio/issues/9627

**Comment by vaxerski** [comment]
are you on legacy_renderer?

**Comment by vaxerski** [comment]
no, it was just a question as legacy_renderer for sure had issues with that

**Comment by vaxerski** [comment]
what's the xdph ver? I assume 1.1. Does this happen on -wlr too?

**Comment by glepnir** [comment]
xdph is `1.1.0-3` i don't install xdpw but the link issue original author solved by switch to wlr. I am not sure.

**Comment by vaxerski** [comment]
this most likely means an issue in selecting a format (BGR <-> RGB)

can I get a verbose log of xdph?

add `-v` to launching xdph and redirect its logs to somewhere (so e.g. `-v > /tmp/xdphlog`) and provide the log from an offending session

try the nuclear script from [here](https://wiki.hyprland.org/Useful-Utilities/Hyprland-desktop-portal/#usage) to make sure it runs correctly

**Comment by glepnir** [comment]
just run that bash script . and some warning give. can be ignore ?

```
xdg-desktop-portal-wlr: no process found

(/usr/lib/xdg-desktop-portal:43243): xdg-desktop-portal-WARNING **: 20:38:22.001: No skeleton to export
```

2. open obs and close after select screen monitor 

the log a bit long .not sure this is you want.

[xdphlog.txt](https://github.com/hyprwm/xdg-desktop-portal-hyprland/files/12803406/xdphlog.txt)

**Comment by vaxerski** [comment]
it's the correct log, thank you

**Comment by vaxerski** [comment]
hm... It forces SHM, what GPU are you using...?

**Comment by glepnir** [comment]
amd rx580sp

**Comment by vaxerski** [comment]
does `wl-screenrec` work? I am weirded out why obs doesn't choose dma

**Comment by glepnir** [comment]
> I am weirded out why obs doesn't choose dma 

then you may need talk with obs developer :)

**Comment by vaxerski** [comment]
well I am working with you first because nobody else has the issue. Can you try wl-screenrec and see if it works? It might be your gpu trying to push weird dma modifiers and not a fault of obs

**Comment by glepnir** [comment]
okay make sure it write in rust right ? after install problem still exist

**Comment by vaxerski** [comment]
what?

**Comment by glepnir** [comment]
![image](https://github.com/hyprwm/xdg-desktop-portal-hyprland/assets/41671631/e8745cc7-b642-4167-93ca-347c5d044414)

**Comment by vaxerski** [comment]
wl-screenrec is a screen recorder utility just like obs. I am asking whether it works, not obs.

**Comment by glepnir** [comment]
lol I misunderstand then..idk what's that tool do haha.. okay I can't use that tool some error through out.

**Comment by vaxerski** [comment]
if it crashes, then it means your GPU is advertising invalid modifiers, and that's why dma fails.

Odd that shm has an invalid format though, hm.

**Comment by glepnir** [comment]
no idea what happen. it works before. but i do `yay` everyday :) so someday it's broken T.T

create an issue on `wl-screenrec` but seems like author not active rencently. so I think the reply will have a delay. 

I don't do nothing special on gpu driver. all installed by `archinstall` script.

**Comment by vaxerski** [comment]
It used to work probably prior to the 1.0 rewrite. Can't see what went wrong during the rewrite though, all works just fine on my end, even with shm.

**Comment by glepnir** [comment]
interesting. everything works fine in your local right. is it possiable to switch to before version to see what happen ?

**Comment by vaxerski** [comment]
if you use arch you can just downgrade from your package cache in /var/cache/pacman/pkg

you can also clone the repo, reset to 0.5 and compile

**Comment by vaxerski** [comment]
can you post the output of `lscpu | grep Byte`

**Comment by glepnir** [comment]
yes I am in arch. output is `Byte Order:                         Little Endian`

**Comment by vaxerski** [comment]
okay so that is ruled out. Thanks.

**Comment by glepnir** [comment]
you are welcome :) lmao so you know what the problem is right :thinking:  ?

**Comment by vaxerski** [comment]
I have no clue so far. Can you also provide a trace log from the working xdpw or xdph <= 0.5 ? Add `-l TRACE > /tmp/xdpw.log` to the cmdline as before.

**Comment by glepnir** [comment]
just want to make sure replace xdph by 0.5 version in `/usr/lib` still work right. need restart machine ? nothing change after replace.

**Comment by glepnir** [comment]
switch to xdpw works fine.

**Comment by vaxerski** [comment]
then provide a trace log from xdpw :)

**Comment by glepnir** [comment]
[xdpw.log](https://github.com/hyprwm/xdg-desktop-portal-hyprland/files/12840692/xdpw.log)

**Comment by vaxerski** [comment]
thank u!!! >///< it seems I see where the fucky-wucky is, but I will have to do some scwubby wubby of the code to find the issue OwO pwease howd on

**Comment by ardishco-the-great** [comment]
Here is the only justified usage of ChatGPT:

Input:
"Hello ChatGPT, could you please de-uwuify this for me?"

> thank u!!! >///< it seems I see where the fucky-wucky is, but I will have to do some scwubby wubby of the code to find the issue OwO pwease howd on

Output:

Of course! Here's the de-uwuified version of your text:

"Thank you! It seems I see where the problem is, but I will have to do some scrubbing of the code to find the issue. Please hold on."

**Comment by vaxerski** [comment]
can you give me the output of `pw-dump` _while screen capturing_ in xdph? (this can be just seeing your screen live in obs)

`pw-dump > somefile.txt` and attach that.

**Comment by vaxerski** [comment]
test with above, should be fixed.

**Comment by glepnir** [comment]
thanks install xdph git version wors fine now.
