### ISSUE TITLE
It works normally at one interval

### ISSUE THREAD

**Issue by DreamMaoMao** [hyprwm/xdg-desktop-portal-hyprland#108]
xdg-desktop-portal-hyprland version:0.5

I needed to start obs twice to successfully record the screen, because the first time it would signal the end of xdg-desktop-portal-hyprland(probably because the previous one didn't exit correctly), and then the second time it would successfully start xdg-desktop-portal-hyprland

so I make a test:

When I first ran
/usr/libexec/xdg-desktop-portal-hyprland
Then start obs to record the screen successfully

Then I close (Ctrl + c)/usr/libexec/xdg-desktop-portal-hyprland
Then starting obs to record the screen will fail

Then I close (Ctrl + c)/usr/libexec/xdg-desktop-portal-hyprland
Then launch obs and record the screen successfully

Then I close (Ctrl + c)/usr/libexec/xdg-desktop-portal-hyprland
Then starting obs to record the screen will fail

It happens over and over again.

![image](https://github.com/hyprwm/xdg-desktop-portal-hyprland/assets/30348075/aebf5796-e790-485b-b3c8-3fd62ff5e210)

**Comment by DreamMaoMao** [comment]
Is there any way to avoid this,

For example, how to clear the previous connection information before each start xdg-desktop-portal-hyprland

**Comment by vaxerski** [comment]
0.5 is horribly outdated and not supported
