### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by kushagra-xo** [hyprwm/xdg-desktop-portal-hyprland#111]
Screenshare dialogs are in light theme, even though i have configured qt5/qt6 to use kvantum (dark theme) via qt5ct/qt6ct. Is there any way to configure it's theme?

**Comment by vaxerski** [comment]
https://wiki.hyprland.org/Useful-Utilities/Hyprland-desktop-portal/#share-picker-doesnt-use-the-system-theme
