### ISSUE TITLE
OBS 29.1.3 crashing on screen/window sharing

### ISSUE THREAD

**Issue by 31JSON** [hyprwm/xdg-desktop-portal-hyprland#112]
On arch, there were recent updates to OBS, xdg-desktop-portal-hyprland, and pipewire. Now OBS is again crashing when trying to screen or window share.

Versions:
obs-studio-tytan652 29.1.3-5
xdg-desktop-portal-hyprland 1.2.1-1
pipewire 1:0.3.81-1

GPUs: Intel and AMD

Tail of the OBS log:
```
info: PipeWire initialized
info: [pipewire] Screencast session created
info: [pipewire] Asking for desktop
info: [pipewire] desktop selected, setting up screencast
error: bmalloc: Allocating 0 bytes is broken behavior, please fix your code! This will crash in future versions of OBS.
error: bmalloc: Allocating 0 bytes is broken behavior, please fix your code! This will crash in future versions of OBS.
error: bmalloc: Allocating 0 bytes is broken behavior, please fix your code! This will crash in future versions of OBS.
error: bmalloc: Allocating 0 bytes is broken behavior, please fix your code! This will crash in future versions of OBS.
info: [pipewire] Server version: 0.3.81
info: [pipewire] Library version: 0.3.81
info: [pipewire] Header version: 0.3.81
info: [pipewire] Created stream 0x5588ea5f4ab0
info: [pipewire] Stream 0x5588ea5f4ab0 state: "connecting" (error: none)
info: [pipewire] Playing stream 0x5588ea5f4ab0
info: [pipewire] Stream 0x5588ea5f4ab0 state: "paused" (error: none)
info: [pipewire] Negotiated format:
info: [pipewire]     Format: 7 (Spa:Enum:VideoFormat:RGBx)
info: [pipewire]     Size: 1912x1157
info: [pipewire]     Framerate: 0/1
info: [pipewire] Stream 0x5588ea5f4ab0 state: "streaming" (error: none)
[1]    17111 segmentation fault (core dumped)  obs
```

**Comment by vaxerski** [comment]
do you have `mbedtls2` installed?

**Comment by 31JSON** [comment]
No, it is not installed. Does it need to be?

**Comment by vaxerski** [comment]
for wl_shm, yes

**Comment by 31JSON** [comment]
`wl_shm` isn't installed either.

**Comment by 31JSON** [comment]
Installing `mbedtls2` and restarting did not fix the issue.

Let me know if there is any other information I can provide that would be helpful.

**Comment by vaxerski** [comment]
well the issue seems to be on your side if anything. Works just fine for me. Does it also happen with xdpw?

**Comment by 31JSON** [comment]
I did a clean install on another computer and it seems to work normally. The install on my streaming computer is an older one from the kernel version 5 days, but is always kept up to date. On the new install, `mbedtls2` was pulled in. What I don't understand is that looking at the output of `pacman -Sii mbedtls2` shows `必要パッケージ         : godot  haxe  julia  neko  retroarch`. Are any of these related to xdph?

**Comment by vaxerski** [comment]
nope, shouldnt be. mbedtls2 is an obs dep anyways, not xdph.

Likely its an obs issue here.

**Comment by jonhoo** [comment]
I've reported this upstream at https://github.com/obsproject/obs-studio/issues/9733

**Comment by jonhoo** [comment]
Fixed upstream in https://github.com/obsproject/obs-studio/pull/9774 (which will be included in OBS 30).
