### ISSUE TITLE
xdg-desktop-portal-hyprland does not start because dbus

### ISSUE THREAD

**Issue by NgoHuy** [hyprwm/xdg-desktop-portal-hyprland#114]
I have problem with recently xdgh, it does not start with error `[LOG] Initializing xdph...
[CRITICAL] Couldn't create the dbus connection ([org.freedesktop.DBus.Error.AccessDenied] Failed to request bus name (Permission denied))
`
I rebuild with git or stable version included hyprland-git and nothing worked.

**Comment by vaxerski** [comment]
means it's already running

**Comment by NgoHuy** [comment]
Again, I said that it did not run. `ps -aux | grep xdg`  doesnot show xdgh on the result. Again, please investigate it before closing the issue as your assume.
![image](https://github.com/hyprwm/xdg-desktop-portal-hyprland/assets/1238112/0f7b848e-2e4b-4557-8d8d-6ca476928d11)

**Comment by vaxerski** [comment]
thats a problem with your dbus then, not xdph

**Comment by NgoHuy** [comment]
why xdgw runs fine, not xdgh? while other runs fine, not xdgh? The bug only appears when I upgraded hyprland, not older version.

**Comment by NgoHuy** [comment]
I add commit to fix this behaviour.

**Comment by piyushyadav0191** [comment]
@NgoHuy  I got same error when running `journalctl --user -xeu xdg-desktop-portal-hyprland.service` . Do you know how to solve it without building source because I am not able to screen share in my browser even though I have everything installed.

**Comment by NgoHuy** [comment]
> @NgoHuy I got same error when running `journalctl --user -xeu xdg-desktop-portal-hyprland.service` . Do you know how to solve it without building source because I am not able to screen share in my browser even though I have everything installed.

can you share your log and version of xdgh?
