### ISSUE TITLE
High CPU usage when exiting Hyprland (#103) is back

### ISSUE THREAD

**Issue by willifan** [hyprwm/xdg-desktop-portal-hyprland#116]
OS: Arch
Kernel: 6.5.6-zen2-1-zen
Hyprland version: 0.30.0-1
xdg-desktop-portal-hyprland version: 1.2.2-1

The same as issue #103 happens again.

I experienced high CPU usage of xdph when exiting before version 1.2.0 but the update fixed it, now it is happening again.
Everything from the original issue is the same, killing the process fixes it.

**Comment by AymanLyesri** [comment]
for me i experience high cpu with xdg-desktop-portal-hyprland and spotify when i logout and login again
