### ISSUE TITLE
XDG-Desktop-Portal-Hyprland seems to be anti-libadwaita theme choice

### ISSUE THREAD

**Issue by 0a00** [hyprwm/xdg-desktop-portal-hyprland#118]
XDG-Desktop-Portal-Hyprland seems to be anti-libadwaita theme choice
![图片](https://github.com/hyprwm/xdg-desktop-portal-hyprland/assets/59482058/a043d058-9e57-46ea-b614-664320257944)

**Comment by vaxerski** [comment]
xdph doesn't use gtk. What are you talking about?

**Comment by 0a00** [comment]
Sorry
