### ISSUE TITLE
Screen share breaks with ultrawide

### ISSUE THREAD

**Issue by NormalFall** [hyprwm/xdg-desktop-portal-hyprland#12]
The broken resolution is 3440x1440 and the good resolution is 1920x1080(Still on the same monitor). It only breaks when screen sharing. App sharing works fine either way.

![20221218_17h12m46s_grim](https://user-images.githubusercontent.com/93881091/208322230-c523b605-8e83-49c1-8dce-c2a07c316223.png)
![20221218_17h17m49s_grim](https://user-images.githubusercontent.com/93881091/208322331-ce0cc55a-564c-4fce-a3c5-56029cd2520a.png)

**Comment by vaxerski** [comment]
most likely an issue with wlr. I'll write my own sharer though in the future.

**Comment by NormalFall** [comment]
Yep. It is the same with xdpw.

**Comment by vaxerski** [comment]
wlroots' screen sharing impl has some issues. Again, I'll probably rewrite it for HL in some time.
