### ISSUE TITLE
Performance issue with hyprland's xdg

### ISSUE THREAD

**Issue by EvilBoi123** [hyprwm/xdg-desktop-portal-hyprland#120]
idk if this issue is already well known but hyprland's performance is little bit laggier (in terms of fps) than wlr's

idk, how to prove it but you have to try. Any request for log or config, i can gladly provide it.

**Comment by vaxerski** [comment]
I need some benchmark. XDP(H/W) should not be a bottleneck here

**Comment by EvilBoi123** [comment]
i've tried using through hyprctl keyword debug:overlay true, but both comparison seems the same. This artifact can only be seen through eyes. 

https://github.com/hyprwm/xdg-desktop-portal-hyprland/assets/102599991/579b29e5-16c4-4c04-be47-0e59d3ccc34f

the sway seems to be run in 60 fps

https://github.com/hyprwm/xdg-desktop-portal-hyprland/assets/102599991/c084eda1-838c-4a7c-9896-aa0db308cac2

hyprland however does not hit the sweet spot. From my gaming eyes i'm guessing around 30 fps.

**Comment by vaxerski** [comment]
if anything, this would imply repeated frames. OBS reports 60fps in both cases

**Comment by Fxzzi** [comment]
Ah, seems like I wrote a dupe issue report then, #201 . Also getting the same issue. Hyprlands capture is most definitely not 60fps compared to the wlrobs plugin with dmabuf or xdpw.

**Comment by issacdowling** [comment]
Can confirm this issue, especially when attempting to capture at 120fps. wlr-obs looks smooth, but using the portal does not. Since I'm looking to use it with Gstreamer, the wlr-obs plugin is not a solution for me.

**Comment by vaxerski** [comment]
should be fixed with a series of patches. Please verify.

**Comment by unjaks** [comment]
> should be fixed with a series of patches. Please verify. I've also added `screencopy:max_fps` to the config, with a default of 120.

nothing seems to have changed, not for me at least. utd

**Comment by Fxzzi** [comment]
yay, looks fixed for me!!

@unjaks, make sure you're on xdph-git. I was also on hyprland-git too.

Also, the option goes in `~/.config/hypr/xdph.conf`, not your `hypr.conf`. Is xdph.conf documented anywhere @vaxerski? I found it pretty easily by searching through the code a little.


https://github.com/hyprwm/xdg-desktop-portal-hyprland/assets/18248986/7ee0ffd6-0789-47ae-bd9d-4908a862d9b7

example of max_fps = 170, its working!!!

**Comment by vaxerski** [comment]
documented on the wiki https://wiki.hyprland.org/Hypr-Ecosystem/xdg-desktop-portal-hyprland/#configuration

**Comment by vaxerski** [comment]
since it's solved, I'm closing this

**Comment by EvilBoi123** [comment]
yup, can confirm it works now, even obs detects the real fps now.
