### ISSUE TITLE
Higher CPU usage after crash

### ISSUE THREAD

**Issue by LamprosPitsillos** [hyprwm/xdg-desktop-portal-hyprland#121]
I installed `Calibre` today , and for some reason it crashes my Hyprland ( or something else, it takes me to SDDM) , i still dont know why.

Before crash :
![2023-10-23_21-34-37_before](https://github.com/hyprwm/xdg-desktop-portal-hyprland/assets/61395246/6c36e202-21e6-4e57-a4e8-aa9dc8da60ae)
After reloging in :
![2023-10-23_21-35-14_after](https://github.com/hyprwm/xdg-desktop-portal-hyprland/assets/61395246/e1b8335c-64f7-4a87-bc1f-94cfc40091a8)

After that i need to reboot to fix the cpu issue.

Info :
```
❯ hyprctl version
Hyprland, built from branch  at commit 4a79718fe8e4601983797d254cce39960827cb02  ().
Tag: 

flags: (if any)
debug



Name: xdg-desktop-portal-hyprland Version: 1.1.0 (nix)

❯ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.58, NixOS, 23.11 (Tapir), 23.11.20231019.7c9cc5a`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.17.1`
 - channels(root): `"nixos-23.05"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```
Steps to reproduce :
`❯ nix run nixpkgs#calibre`

**Comment by vaxerski** [comment]
This was fixed in 1.2.0 - 1.2.3
