### ISSUE TITLE
restore tokens only slightly working

### ISSUE THREAD

**Issue by naps62** [hyprwm/xdg-desktop-portal-hyprland#123]
Hi
not sure if this is an issue here or upstream (sorry, I don't have much understanding about this whole stack)

the restore token seems to have very limited functionality. namely:
- in chrome + google meet screenshare, it doesn't work at all. I get asked twice (due to #11), and selecting restore token on both of those doesn't change anything. the next time I screenshare, even within the same call, I have to select everything again
- in OBS, it works, but only for the next run. 2 runs later and the window picker is back

**Comment by vaxerski** [comment]
first thing is a chromium issue

**Comment by vince6794** [comment]
OBS case: same for me. Every time I boot OBS I've to reselect all the monitors (screen sharing) in all the scenes. Very annoying.
Any idea on how to fix this?

**Comment by jh-devv** [comment]
+1 Happening still, makes the "Restore tokens" kinda useless

**Comment by vaxerski** [comment]
point 2 fixed in above commit, I'll regard this as solved.

**Comment by jh-devv** [comment]
> point 2 fixed in above commit, I'll regard this as solved.

Can you make an hotfix release for this?

**Comment by vaxerski** [comment]
I can

**Comment by vaxerski** [comment]
https://github.com/hyprwm/xdg-desktop-portal-hyprland/releases/tag/v1.3.1

**Comment by different-name** [comment]
> first thing is a chromium issue

Has anyone made an issue upstream?
