### ISSUE TITLE
zwlr_screencopy_frame_v1 - invalid buffer dimensions

### ISSUE THREAD

**Issue by psoldunov** [hyprwm/xdg-desktop-portal-hyprland#128]
Hi!

In tools like grim or hyprpicker I get following zwlr_screencopy_frame_v1 error:

`zwlr_screencopy_frame_v1@8: error 1: invalid buffer dimensions`

Using portal version 1.2.4, Fedora 39 from this [COPR](https://copr.fedorainfracloud.org/coprs/solopasha/hyprland/).

Thanks!

**Comment by vaxerski** [comment]
https://github.com/hyprwm/Hyprland/issues/3795
