### ISSUE TITLE
VRAM leak ?

### ISSUE THREAD

**Issue by rainDiX** [hyprwm/xdg-desktop-portal-hyprland#129]
OS: Arch
Kernel: 6.6.1-zen1-1-zen
mesa version: 1:23.2.1
Hyprland version: 0.30.0
xdg-desktop-portal-hyprland version: 1.2.4
GPU:  AMD Radeon RX 5500 XT (navi14)

After screen-sharing for about an hour on armcord, I noticed that xdph was using more than 2.5GB of VRAM. Happened multiple times already.
I do not know if this is relevant but I was screen-sharing windows, not entire screen.

Current workaround is to restart xdph after sharing.

![Screenshot_from_2023-11-12_21_11_45](https://github.com/hyprwm/xdg-desktop-portal-hyprland/assets/34621487/87182a97-cd43-4f6a-950d-6e5c3348497a)

**Comment by ashbir** [comment]
OS: Nobara 38
Kernel: 6.5.9-201.fsync.fc38.x86_64
Mesa: 23.2.1
Hyprland: 0.32.3
xdg-desktop-portal-hyprland: 1.2.4
GPU: AMD Radeon Vega 8 Graphics
I have similar issue with vram memory leak. 
I use zoom web app on firefox to share my screen, after I stop the screen sharing, the xdph vram is not decreased. If I shared again, the vram keep increasing. I need to kill xdph to reduce the vram

![image](https://github.com/hyprwm/xdg-desktop-portal-hyprland/assets/5442293/e2e57384-ea90-4084-950c-f6a83181097b)

**Comment by shvedes** [comment]
**Same problem**
OS: Arch Linux
Kernel: 6.6.1-arch1-1
Mesa: 23.2.1
Hyprland: 0.32.3
xdg-desktop-portal-hyprland: 1.2.4-1

I noticed this when playing with MangoHud enabled. I played DeathStranding, so I didn’t believe that with this game my system could consume more than 10 GB of video memory, after I opened nvtop I realized that the problem was xdph

![image](https://github.com/hyprwm/xdg-desktop-portal-hyprland/assets/84767665/8f53e0cb-1254-433f-9dab-835fb87cf48b)

**Comment by vaxerski** [comment]
has this improved with 8d3538e113341f586682e5a996ba5f015a22ecdd ?

**Comment by ashbir** [comment]
@vaxerski, I have tried https://github.com/hyprwm/xdg-desktop-portal-hyprland/commit/8d3538e113341f586682e5a996ba5f015a22ecdd  and the screenshare doesn't leak vram anymore

**Comment by rainDiX** [comment]
Thanks @vaxerski, on https://github.com/hyprwm/xdg-desktop-portal-hyprland/commit/8d3538e113341f586682e5a996ba5f015a22ecdd  The vram is now freed when the screenshare is over. 

Still another bug, less annoying tho, is that xdph use an insane amount a vram when sharing a window and resizing it, should I open another issue for this one?

**Comment by vaxerski** [comment]
na, thats connected to this one most likely, I'll see later today.

**Comment by vaxerski** [comment]
fixed in 716da5e0f3756df9ad0edf948e10d80aecf9019b
