### ISSUE TITLE
config file?

### ISSUE THREAD

**Issue by sharak** [hyprwm/xdg-desktop-portal-hyprland#133]
Hey, I'm trying to locate config file to add somethink like this:
```
[screencast]
exec_before=blah blah blah
exec_after=blah blah
```
I've tried with `$XDG_CONFIG_HOME/xdg-desktop-portal-hyprland/config` and `$XDG_CONFIG_HOME/xdg-desktop-portal-wlr/Hyprland` with no luck.

Is it possible to execute a command before screen share?

**Comment by vaxerski** [comment]
there is no config in xdph

**Comment by sharak** [comment]
Thank you.

So is it impossible to replicate the above scenario? My idea is to mute notifications when I am screen sharing.

**Comment by vaxerski** [comment]
you can do that by listening to hyprland's socket2 for the screencast event: https://wiki.hyprland.org/IPC/#events-list

**Comment by sharak** [comment]
Thank you guy!

I hadn't thought of that possibility ':)
