### ISSUE TITLE
XDPH Fails to Start

### ISSUE THREAD

**Issue by jordan-josephs** [hyprwm/xdg-desktop-portal-hyprland#138]
Upon starting Hyprland XDPH fails to start. Manually starting only results in the following error message 

[CRITICAL] Couldn't create the dbus connection ([org.freedesktop.DBus.Error.FileExists] Failed to request bus name (File exists))

I have checked the journal and systemd output to no avail. What file is it complaining is existing?

**Comment by jordan-josephs** [comment]
Somehow this was fixed by setting up a startup script that only has "exec Hyprland" and calling it that way.

**Comment by pjrulez** [comment]
I'm running into a similar issue today.

systemctl --user status xdg-desktop-portal-hyprland.service

× xdg-desktop-portal-hyprland.service - Portal service (Hyprland implementation)
     Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal-hyprland.service; static)
     Active: failed (Result: exit-code) since Tue 2025-01-28 16:10:19 EST; 33min ago
 Invocation: 1093bfe3e58d4e47bf89703772242bca
   Main PID: 1475 (code=exited, status=1/FAILURE)

gen systemd[946]: xdg-desktop-portal-hyprland.service: Scheduled restart job, restart counter is at 5.
gen systemd[946]: xdg-desktop-portal-hyprland.service: Start request repeated too quickly.
gen systemd[946]: xdg-desktop-portal-hyprland.service: Failed with result 'exit-code'.
gen systemd[946]: Failed to start Portal service (Hyprland implementation).


journalctl -xe | grep dbus
...
gen xdg-desktop-portal-hyprland[1475]: [CRITICAL] Couldn't create the dbus connection ([org.freedesktop.DBus.Error.FileExists] Failed to request bus name (File exists))


starting it manually:
/usr/lib/xdg-desktop-portal-hyprland -V
xdg-desktop-portal-hyprland v1.3.9

/usr/lib/xdg-desktop-portal-hyprland --verbose
[LOG] Initializing xdph...
[CRITICAL] Couldn't create the dbus connection ([org.freedesktop.DBus.Error.FileExists] Failed to request bus name (File exists))

The service file:
[Unit]
Description=Portal service (Hyprland implementation)
PartOf=graphical-session.target
After=graphical-session.target
ConditionEnvironment=WAYLAND_DISPLAY

[Service]
Type=dbus
BusName=org.freedesktop.impl.portal.desktop.hyprland
ExecStart=/usr/lib/xdg-desktop-portal-hyprland
Restart=on-failure
Slice=session.slice

hyprland --version
Hyprland 0.46.2 built from branch  at commit 0bd541f2fd902dbfa04c3ea2ccf679395e316887  (version: bump to 0.46.2).
Date: Thu Dec 19 19:26:47 2024
Tag: v0.46.2, commits: 5566
built against:
 aquamarine 0.7.1
 hyprlang 0.6.0
 hyprutils 0.4.0
 hyprcursor 0.1.11
 hyprgraphics 0.1.1


flags set:
debug


env variables are set to the ml4w settings, which are also in the hyprland docs. 

Please help :|
