### ISSUE TITLE
Failed to start Portal service (Hyprland implementation)

### ISSUE THREAD

**Issue by Mahgozar** [hyprwm/xdg-desktop-portal-hyprland#144]
### Hyprland Version

Hyprland, built from branch main at commit 6fb1b89b982eea26ecae75b93f1742537c4f31ae dirty (makefile: add rm hyprpm for uninstall (4086)). Tag: v0.33.1-9-g6fb1b89b

### Bug or Regression?

Bug

### Description

after the update every time i boot the system waybar and firefox take a very long time to lunch fixes suggested in the wiki dont work

im rewriting this here cause of the wrong tracker sorry for the mistake 
### How to reproduce

happens after the latest update of hyprland with rebooting the system 

### Crash reports, logs, images, videos

results of the systemctl --user status xdg-desktop-portal-hyprland 
```
× xdg-desktop-portal-hyprland.service - Portal service (Hyprland implementation)
     Loaded: loaded (/usr
/lib/systemd/user/xdg-desktop-portal-hyprland.service; static)
     Active: failed (Result: exit-code) since Sat 2023-12-09 14:44:11 +0330; 5min ago
   Main PID: 2729 (code=exited, status=127)
        CPU: 1ms

Dec 09 14:44:11 haku systemd[2370]: xdg-desktop-portal-hyprland.service: Scheduled restart job, r
estart counter is at 5.
Dec 09 14:44:11 haku systemd[2370]: xdg-desktop-portal-hyprla
nd.service: Start request repeated too quickly.
Dec 09 14:44:11 haku systemd[2370]: xdg-desktop-portal-hyprla
nd.service: Failed with result 'exit-code'.
Dec 09 14:44:11 haku systemd[2370]: Failed to start Portal service (Hyprl
and implementation).
```
[hyprland.log](https://github.com/hyprwm/Hyprland/files/13623911/hyprland.log)

**Comment by vaxerski** [comment]
can you show the logs from that run?

**Comment by Mahgozar** [comment]
Do you mean the results of this command? 
systemctl --user status xdg-desktop-portal-hyprland

Cause I've included those already

If not can you tell me where can I find them?

**Comment by vaxerski** [comment]
systemctl logs should be good enough, but you only provided the last part. I need the full thing. You can see them in `journalctl -u xdg-desktop-portal-hyprland`

**Comment by Mahgozar** [comment]
whe i run the systemctl logs command it gives me the same message that i sent here but the journalctl one says no entry

**Comment by Mahgozar** [comment]
ok so i installed xdg-desktop-portal-wlr on the system apparently it wasn't there before and it fixed my startup problem 
but i can't do the screen sharing, and when i try the screen share tips in the wiki we go back to where we started with the startup problem. dont know if it helps just wanted to add it here

**Comment by vaxerski** [comment]
use the nuclear script from the wiki and provide logs from that, then. https://wiki.hyprland.org/Useful-Utilities/Hyprland-desktop-portal/

**Comment by Mahgozar** [comment]
sorry for the late answer
the problem was with my system missing the  libsdbus-c++.so.1 which prevented the portal to launch
now its fixed 
sorry for the wasted time

**Comment by divital-coder** [comment]
Hiya guys i am facing the same issue, and i seem to have sdbus-cpp already installed, wondering what could be the issue on my system.

**Comment by chiefdinkan** [comment]
> same here too

**Comment by rudyon** [comment]
same issue

**Comment by DTarbet** [comment]
same here as well

**Comment by Sayykii** [comment]
same issue here

**Comment by DoktorMike** [comment]
Same here.
