### ISSUE TITLE
QT Theme seems to be ignore even when `QT_QPA_PLATFORMTHEME` has value set

### ISSUE THREAD

**Issue by mxaddict** [hyprwm/xdg-desktop-portal-hyprland#145]
I've set my environment variable `QT_QPA_PLATFORMTHEME` to `gtk2` but the sharescreen and other qt apps seem to not honor the gtk theme set.

Some other apps like `nautilus`, `audacity`, `gparted`, `kde-polkit` also don't use the correct theme.

I've run the following:
```
gsettings set org.gnome.desktop.interface gtk-theme "Dracula"
gsettings set org.gnome.desktop.interface icon-theme "Dracula"
gsettings set org.gnome.desktop.interface color-scheme prefer-dark
```

NOTES: `chromium`, `nemo` and some other apps seem to be using the correct theme.

**Comment by vaxerski** [comment]
https://wiki.hyprland.org/Useful-Utilities/Hyprland-desktop-portal/#share-picker-doesnt-use-the-system-theme ?

**Comment by mxaddict** [comment]
> https://wiki.hyprland.org/Useful-Utilities/Hyprland-desktop-portal/#share-picker-doesnt-use-the-system-theme ?

I've run both of those.

**Comment by mxaddict** [comment]
Additionally, I have these env values set:
```
env = QT_QPA_PLATFORM,wayland;xcb
env = GTK_THEME,Dracula
env = GDK_BACKEND,wayland,x11
env = CLUTTER_BACKEND,wayland
env = XDG_CURRENT_DESKTOP,Hyprland
env = XDG_SESSION_TYPE,wayland
env = XDG_SESSION_DESKTOP,Hyprland
env = QT_AUTO_SCREEN_SCALE_FACTOR,1
env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
env = QT_QPA_PLATFORMTHEME,gtk2
```

**Comment by mxaddict** [comment]
Also for `nautilus` when I run it from terminal as `GTK_THEME=Dracula nautilus` it seems to pickup the theme, but I have that env set in my `hyprland.conf` so I'm stumped 🤣 

I must have burked my config somewhere 🤷🏼

**Comment by mxaddict** [comment]
Ok, so for some reason after I installed `xdg-desktop-portal-gtk` used that for a bit, then switched back to `xdg-desktop-portal-hyprland` it seems to now use the correct theme for screen share popup...

Not sure what to make of that.

GTK4 themed apps also now seem to use the dark mode `but only if I keep xdg-desktop-portal-gtk` installed even if not running? 🤷🏼

**Comment by mxaddict** [comment]
> Ok, so for some reason after I installed `xdg-desktop-portal-gtk` used that for a bit, then switched back to `xdg-desktop-portal-hyprland` it seems to now use the correct theme for screen share popup...
> 
> Not sure what to make of that.
> 
> GTK4 themed apps also now seem to use the dark mode `but only if I keep xdg-desktop-portal-gtk` installed even if not running? 🤷🏼

Nvm, I was still running `xdg-desktop-portal-gtk` so it seems that GTK4 apps are not using correct theme settings when `xdg-desktop-portal-hyprland` is running, but work correctly if you use `xdg-desktop-portal-gtk`

But as for the QT apps, for some reason they are now working on bot (I guess I just had to restart xdg-desktop-portal)

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/xdg-desktop-portal-hyprland/assets/43317083/87cd28d8-d3e6-4f29-b60a-c3cd72fc04bf)

https://wiki.hyprland.org/Useful-Utilities/Hyprland-desktop-portal/

**Comment by mxaddict** [comment]
> ![image](https://private-user-images.githubusercontent.com/43317083/289957374-87cd28d8-d3e6-4f29-b60a-c3cd72fc04bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0MDM4NDcsIm5iZiI6MTcwMjQwMzU0NywicGF0aCI6Ii80MzMxNzA4My8yODk5NTczNzQtODdjZDI4ZDgtZDNlNi00ZjI5LWI2MGEtYzNjZDcyZmMwNGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDE3NTIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhODYyM2EyNzQzODZkYjdmY2I2YjFlMGY0MTYyZDg2YTAxNjZmY2Y1NjVhMWE4NzZmMjI4ODFiZDAyZGZiY2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1pXQW0ow98IQSPP90j1OJewegQM6vRK--c0EG9A2tsU)
> 
> https://wiki.hyprland.org/Useful-Utilities/Hyprland-desktop-portal/
> 
> xdph doesn't implement the preferred theme protocol either.

I see, what are the features implemented in `xdg-desktop-portal-hyprland` that are not in `xdg-desktop-portal-gtk` ?

Would it make sense to switch to `xdg-desktop-portal-gtk` and not have `xdg-desktop-portal-hyprland` running at all?

**Comment by vaxerski** [comment]
no. gtk only implements gtk stuff. a file picker, color theme, etc.

hyprland implements screensharing, screencopy and global shortcuts.

**Comment by mxaddict** [comment]
> no. gtk only implements gtk stuff. a file picker, color theme, etc.
> 
> hyprland implements screensharing, screencopy and global shortcuts.

I see, so optimally I would need both?

**Comment by vaxerski** [comment]
yes

**Comment by mxaddict** [comment]
Thanks for the help!

**Comment by helixoid** [comment]
Why not implement the important stuff from kde and gtk portal for consistency and not depending on running more than one xdg-desktop-portal implementation?

**If not all, then at least the theming portals for qt and gtk apps.**

Again, this is just a suggestion as I really love this project and want it to improve the integration of apps (especially flatpaks) in the desktop.

**Comment by fufexan** [comment]
The XDG Portal specification supports running multiple portals at the same time, and using only specific interfaces from each of those. It is way easier to rely on what's already built and working, and not rewrite everything from scratch.

**Comment by fufexan** [comment]
Yes, that's how it was a while ago. Since a few months ago, the portal specification allows multiple portals to coexist, and only needed ones to be started for a given environment. For Hyprland, those are the gtk and hyprland portals. That's why the warning was removed from Hyprland.

**Comment by helixoid** [comment]
> Yes, that's how it was a while ago. Since a few months ago, the portal specification allows multiple portals to coexist, and only needed ones to be started for a given environment. For Hyprland, those are the gtk and hyprland portals. That's why the warning was removed from Hyprland.

Got it!
