### ISSUE TITLE
Support `OpenURI` Interface

### ISSUE THREAD

**Issue by KorigamiK** [hyprwm/xdg-desktop-portal-hyprland#146]
As used by `NewsFlash` opening links throws this error:

```sh
Failed to open URL: ZBus Error: org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.OpenURI” on object at path /org/freedesktop/portal/desktop
```

Since no interface for `OpenURI` is currently present:

![Screenshot_2023-12-16-16-47-27_17095](https://github.com/hyprwm/xdg-desktop-portal-hyprland/assets/72932688/e262a322-6780-4d4f-8236-ca722dc827d3)

A lot of hyprland users would appreciate this addition,
the default browser should be queried through `exo-open` or `xdg-mime` if needed.

**Comment by vaxerski** [comment]
why not just use -gtk

**Comment by KorigamiK** [comment]
> why not just use -gtk

I'm not sure, wouldn't it conflict with existing hyprland portal?

**Comment by vaxerski** [comment]
no

**Comment by KorigamiK** [comment]
> no

Understandable

**Comment by jonvemo** [comment]
Why hasn't this been added to the Hyprland portal? If not for this I'd not run Gtk as well

**Comment by fufexan** [comment]
What's wrong with the gtk portal? It implements a bunch of stuff already, so we don't have to.

**Comment by KorigamiK** [comment]
> What's wrong with the gtk portal? It implements a bunch of stuff already, so we don't have to.

This is because installing the gtk portal causes issues with some applications like file-roller

> I started having the same problem after installing flatpak. Some of the apps that would have delayed start were evince, eog, nemo and fileroller
> Uninstalling flatpak alone did not solve it, but after also removing xdg-desktop-portal and xdg-desktop-portal-gtk solved it. Thanks!

https://bbs.archlinux.org/viewtopic.php?id=243526

**Comment by seyfu-t** [comment]
@KorigamiK  could the kde portals work better here maybe?

**Comment by KorigamiK** [comment]
> @KorigamiK  could the kde portals work better here maybe?

I've switched to using gnome portal for now

**Comment by seyfu-t** [comment]
Ok, I tried kde with little success, went back to gtk
