### ISSUE TITLE
First display capture works fine, subsequent display captures show black screens (on 1.2.6; 1.2.5 works fine)

### ISSUE THREAD

**Issue by DJXJD** [hyprwm/xdg-desktop-portal-hyprland#148]
As is said in the title. This seems to be the case regardless of what application is doing the capture.

[Here](https://github.com/hyprwm/xdg-desktop-portal-hyprland/files/13799960/xdg-desktop-portal-hyprland.log) is a log of:

1. Starting a pipewire screen capture in OBS
2. Noticing it working
3. Removing the screen capture
4. Starting another pipewire screen capture in OBS
5. Noticing it not working

**Comment by diniamo** [comment]
54a30259be0dd196ffc260d6a52b6bbdbf1d5273 should fix this

**Comment by Zambieslar** [comment]
I just tested on 1.2.5 being able to reproduce the same issue. So this seems to go back farther than that.

**Comment by Limbozz-ms** [comment]
I've downgraded to 1.2.5 and it works like it's supposed to.

**Comment by JanValiska** [comment]
> [54a3025](https://github.com/hyprwm/xdg-desktop-portal-hyprland/commit/54a30259be0dd196ffc260d6a52b6bbdbf1d5273) should fix this

Tested on Nvidia card. Works like charm. Before fix I got "[screencopy] Couldn't obtain a format from dma" every time I restarted sharing. So this will probably fix also issue: https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/131

Thank you.

**Comment by rettetdemdativ** [comment]
> [54a3025](https://github.com/hyprwm/xdg-desktop-portal-hyprland/commit/54a30259be0dd196ffc260d6a52b6bbdbf1d5273) should fix this

Can also confirm that this fixed the problem for me (Intel integrated graphics).
