### ISSUE TITLE
Region sharing results in xdg-desktop-portal crashing

### ISSUE THREAD

**Issue by rubyowo** [hyprwm/xdg-desktop-portal-hyprland#15]
When selecting the region sharing option, slurp opens, i select a region, and then  `xdg-desktop-portal` errors with `A backend call failed: Operation not permitted`. I use nixos, and haven't tried building and testing locally.

**Comment by vaxerski** [comment]
that's not a crash...?

Zero logs, zero anything. Doesn't happen to me. Region sharing is not working in general due to issues in wlroots, and it will be rewritten by me some day anyways
