### ISSUE TITLE
can't build from source using aur package

### ISSUE THREAD

**Issue by liaminventions** [hyprwm/xdg-desktop-portal-hyprland#155]
error: https://pastebin.com/raw/MJumCxY7

it worked fine when building from source using the instructions from readme.md though...

**Comment by liaminventions** [comment]
the package is "xdg-desktop-portal-hyprland-git" btw

**Comment by vaxerski** [comment]
AUR package needs to be updated. I'll do it in a sec.

**Comment by vaxerski** [comment]
should be fixed

**Comment by vaxerski** [comment]
it will be not working properly tho until https://github.com/hyprwm/xdg-desktop-portal-hyprland/pull/154

**Comment by liaminventions** [comment]
ok (it doesn't work yet)
<details>
  <summary>new error:</summary>

  Could not open input file: No such file or directory

  Could not open input file: No such file or directory

  Could not open input file: No such file or directory

  Could not open input file: No such file or directory

-- Configuring done (0.9s)

CMake Error at CMakeLists.txt:68 (target_sources):

  Cannot find source file:

    protocols/hyprland-global-shortcuts-v1-protocol.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm
  .ccm .cxxm .c++m .h .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90
  .f95 .f03 .hip .ispc
Call Stack (most recent call first):
  CMakeLists.txt:82 (protocol)

  </details>
  

btw this really isn't that bad because i can still use the new version of XDPH manually (makefile) and it works great (i can screenshare again! :) )
