### ISSUE TITLE
[CMake] Fails to pass LDFLAGS with system sdbus-cpp

### ISSUE THREAD

**Issue by jbeich** [hyprwm/xdg-desktop-portal-hyprland#157]
Affects [FreeBSD](https://wiki.freebsd.org/WarnerLosh/UsrLocal#Library_paths) and other BSDs. Not sure why Nix isn't affected given it uses different prefix for each package. To reproduce install `sdbus-cpp` outside of `/usr` and `/usr/local` thus not part of default C compiler search path.

```
$ git clone https://github.com/Kistler-Group/sdbus-cpp
$ cd sdbus-cpp
$ cmake -DCMAKE_INSTALL_PREFIX:PATH=/tmp/sdbus-cpp_prefix -B /tmp/sdbus-cpp_build -G Ninja
$ cmake --build /tmp/sdbus-cpp_build
$ cmake --install /tmp/sdbus-cpp_build
$ export PKG_CONFIG_PATH=/tmp/sdbus-cpp_prefix/lib/pkgconfig

$ git clone https://github.com/hyprwm/xdg-desktop-portal-hyprland
$ cd xdg-desktop-portal-hyprland
$ cmake -DCMAKE_INSTALL_PREFIX:PATH=/tmp/xdg-desktop-portal-hyprland_prefix -B /tmp/xdg-desktop-portal-hyprland_build -G Ninja
$ cmake --build /tmp/xdg-desktop-portal-hyprland_build
[...]
ld: error: unable to find library -lsdbus-c++

$ pkg-config --libs-only-L sdbus-c++
-L/tmp/sdbus-cpp_prefix/lib
```
Looks like `target_link_libraries` uses plain `sdbus-c++` instead of the imported target:
https://github.com/hyprwm/xdg-desktop-portal-hyprland/blob/c0b606460a099efdea48347aeb40b01af3d9af1c/CMakeLists.txt#L45
https://github.com/hyprwm/xdg-desktop-portal-hyprland/blob/c0b606460a099efdea48347aeb40b01af3d9af1c/CMakeLists.txt#L61

**Comment by jbeich** [comment]
Looks like `target_link_libraries` uses plain `sdbus-c++` instead of `SDBUS` as imported target.

**Comment by fufexan** [comment]
Yes, did that so that even if it's not found through pkg-config, we can still add it through the subproject. Should I try adding it conditionally with `SDBUS` using `if`?

**Comment by jbeich** [comment]
Why not `add_library(SDBUS ALIAS sdbus-c++)` under `if(NOT SDBUS_FOUND)`?

**Comment by fufexan** [comment]
Didn't know about that, thanks! I'll add it now.

**Comment by jbeich** [comment]
Minor correction, `SDBUS` should probably be `PkgConifg::SDBUS`, both in `target_link_libraries` and `add_library`

**Comment by fufexan** [comment]
https://github.com/hyprwm/xdg-desktop-portal-hyprland/commit/df8c154f5793e71796e76004812f2a03eba67e88 seems to work on Nix, I hope it also works for you.

**Comment by jbeich** [comment]
I confirm, builds fine.
