### ISSUE TITLE
[CMake] Fails to auto-start via DBus activation due to relative path

### ISSUE THREAD

**Issue by jbeich** [hyprwm/xdg-desktop-portal-hyprland#159]
Regressed by #154 due to using `CMAKE_INSTALL_LIBEXECDIR` without `_FULL` infix.

```
$ cmake -DCMAKE_INSTALL_PREFIX:PATH=/tmp/xdg-desktop-portal-hyprland_prefix -B /tmp/xdg-desktop-portal-hyprland_build -G Ninja
$ cmake --build /tmp/xdg-desktop-portal-hyprland_build
$ cmake --install /tmp/xdg-desktop-portal-hyprland_build
$ fgrep Exec /tmp/xdg-desktop-portal-hyprland_prefix/share/dbus-1/services/org.freedesktop.impl.portal.desktop.hyprland.service
Exec=libexec/xdg-desktop-portal-hyprland
```

**Comment by fufexan** [comment]
Should we use `_FULL` everywhere?

**Comment by jbeich** [comment]
Mainly with `configure_file`

**Comment by jbeich** [comment]
BTW, Meson support is probably partially broken atm due to changes in placeholder names (e.g., `@libexecdir@` -> `@LIBEXECDIR@`).

**Comment by jbeich** [comment]
Nevermind, I'll file a separate issue about Meson. Until removed it's still supported.

**Comment by fufexan** [comment]
> Mainly with `configure_file`

So, only for `set(LIBEXECDIR ...)`?

**Comment by jbeich** [comment]
Yep, `install` works fine after 86a94c3e4edb.

**Comment by fufexan** [comment]
Done in 1c802128f6cc3db29a8ef01552b1a22f894eeefd.

**Comment by jbeich** [comment]
I confirm, works fine now.
