### ISSUE TITLE
OBS disconnects from portal whilst doing screen capture

### ISSUE THREAD

**Issue by BrodieRobertson** [hyprwm/xdg-desktop-portal-hyprland#162]
### Hyprland Version

0.34.0-1

### Portal Version

1.2.6-1

### Description

During use OBS will disconnect from the portal whilst doing a screen capture under a couple of conditions.

## Case 1
1. Create an OBS Screen Capture
2. Mark the capture as hidden in OBS
3. Switch to another workspace in Hyprland
4. Unhide the screen capture, it should now be frozen

## Case 2
1. Create an OBS Screen Capture on an OBS scene
2. Switch to another OBS scene
3. Whilst on this scene switch to another workspace in Hyprland
4. The screen capture should now be frozen

There is a mostly functional work around, if you create a screen capture and then use the OBS "Paste (Reference)" function to make a pointer to the capture on every single scene, then instead of marking it as hidden just put it behind everything. However this also seems to randomly freeze, I have not found consistent replication conditions for this.

You suggested on the stream this may be related to the lack of pause functionality being implemented in the portal

**Comment by fufexan** [comment]
Have you tried updating to 1.3.0? Afaik it fixed a similar issue of another user.

**Comment by BrodieRobertson** [comment]
I didn't realize a new version shipped. I've updated and at least for the first 2 cases it's still displaying the same behaviour, the workaround breaking is a bit harder to tell but considering the others it's safe to say it probably still breaks.

**Comment by fufexan** [comment]
Did this also happen in 1.2.5 or earlier versions? If not, could you bisect?

**Comment by BrodieRobertson** [comment]
I'm not entirely sure, I'm only recently back on Hyprland and it's been happening whilst I've been here

**Comment by fufexan** [comment]
Alright, then I'm not sure. @vaxerski might know more.

**Comment by vaxerski** [comment]
sorry for the wait I am a bit sick and feeling generally unwell today
