### ISSUE TITLE
Pipewire Issue: First Screen Capture With OBS Works, Any Subsequent Is Black

### ISSUE THREAD

**Issue by mcmah309** [hyprwm/xdg-desktop-portal-hyprland#174]
Original detailed issue report: https://github.com/obsproject/obs-studio/issues/10148

First OBS screen capture works as expected, deleting the source or exiting, and recreating results in a black screen. The only fix is to log out of the graphical session and log back in. Or run
```
systemctl --user restart dbus.service
```
This restarts the issue - works for the first and none after.

Journald culprit
```
Jan 26 18:10:26 nixos wireplumber[202735]: <WpSiStandardLink:0x79e020> 1 of 1 PipeWire links failed to activate
```

**Comment by mtwb47** [comment]
You can try to restart the portal.  `systemctl --user status xdg-desktop-portal-hyprland`

This is also happening to me. As mentioned in #172

**Comment by vaxerski** [comment]
#172
