### ISSUE TITLE
Make screen sharing dialog more responsive and/or allow resizing

### ISSUE THREAD

**Issue by devtrends** [hyprwm/xdg-desktop-portal-hyprland#175]
The screen sharing dialog cuts off text when certain fonts are used:

![image](https://github.com/hyprwm/xdg-desktop-portal-hyprland/assets/1749205/a00a9146-f0c5-410a-a3c8-fe791089a501)

I have tried resizing this with a window rule but it doesn't have any effect:

    windowrule = size 600 300, title:MainPicker$

**Comment by vaxerski** [comment]
There was a MR for that (#173) but the author for some reason got frustrated and closed it. I might remake the thing to be resizeable.

**Comment by rurigk** [comment]
> There was a MR for that (#173) but the author for some reason got frustrated and closed it. I might remake the thing to be resizeable.

Sorry i had a very very bad day, that mr was the product of frustration of not being able to resize and restore the size of the dialog

I think the easy way for the problem to remembering the size its to save it on /tmp and dont worry about any file
It will forget the size but just at least it will remember when the user is using the dialog

I will reopen the MR you can use the code if you want i just wanted a better experience for me and share it with others
I also apologize for closing the MR

You can cherry pick the size remembering thing if you really dont want the size to be remembered, in that case i will mantain the fork for personal use

**Comment by vaxerski** [comment]
I believe remembering the size is not really needed as we have windowrules to deal with that. Adding more config files just because we wanna remember the size sounds kinda pointless

**Comment by rurigk** [comment]
This should be fixed with #173
@devtrends can you give it a try?

**Comment by devtrends** [comment]
Looks good to me. Window is resizable and respects window rules. It seems to remember last size (unless you force close dialog) Position of Allow a restore token on left is better. Only slight issue is the display of long window names (see 2nd item down) Arguably showing the start and ellipsizing might be better but really not a big deal. Nice job

![image](https://github.com/hyprwm/xdg-desktop-portal-hyprland/assets/1749205/87b61b4a-baac-4c94-9b1e-9b15912eee87)

**Comment by rurigk** [comment]
I'm gonna fix this

**Comment by rurigk** [comment]
@devtrends This problem should be solved by #176 can you give it a try?

**Comment by devtrends** [comment]
@rurigk Perfect. Just tried it and it looks great.

![image](https://github.com/hyprwm/xdg-desktop-portal-hyprland/assets/1749205/fc5a7ad9-e05b-44ff-b1c5-be1d74fd5ab9)
