### ISSUE TITLE
libhyprlang.so.0: cannot open shared object file

### ISSUE THREAD

**Issue by grappas** [hyprwm/xdg-desktop-portal-hyprland#181]
On archlinux. Both hyprlang and xdg-desktop-portal-hyprland are git versions (installed via AUR).

find /usr | grep libhyprlang : 
```
/usr/lib/libhyprlang.so
/usr/lib/libhyprlang.so.0.4.0
/usr/lib/libhyprlang.so.1
```

**Comment by vaxerski** [comment]
well sover got bumped to 1, so you have to recompile xdph

**Comment by grappas** [comment]
aww... shit. I thought I already did it. Sorry for bothering you. Case closed.
