### ISSUE TITLE
Service failing if using `-git` version aur

### ISSUE THREAD

**Issue by niksingh710** [hyprwm/xdg-desktop-portal-hyprland#182]
```bash
[Unit]
Description=Portal service (Hyprland implementation)
PartOf=graphical-session.target
After=graphical-session.target
ConditionEnvironment=WAYLAND_DISPLAY

[Service]
Type=dbus
BusName=org.freedesktop.impl.portal.desktop.hyprland
ExecStart=/home/niksingh710/.cache/yay/xdg-desktop-portal-hyprland-git/pkg/xdg-desktop-portal-hyprland-git/usr/lib/xdg-desktop-portal-hyprland
Restart=on-failure
Slice=session.slice
```

This is how the service is looking.
Also check [comments here](https://aur.archlinux.org/packages/xdg-desktop-portal-hyprland-git)

**Comment by vaxerski** [comment]
it is poorly maintained cuz it's owned by kainoa and I dont have time or knowledge to properly maintain it.

**Comment by niksingh710** [comment]
> it is poorly maintained cuz it's owned by kainoa and I dont have time or knowledge to properly maintain it.

Aah, thought you maintain it as your name was mentioned there.
Though no discussion remains here as it seems to be only fixable in xdph package and that will be updated by arch maintainers.

**Comment by vaxerski** [comment]
also the last comment there if thats what you are referring to is due to an update. Recompile xdph.

**Comment by niksingh710** [comment]
if anyone else facing this 

then i will recommend to use the nuclear solution from the wiki

**Comment by salimp2009** [comment]
> if anyone else facing this
> 
> then i will recommend to use the nuclear solution from the wiki

what is the nuclear option. I could not see in the wiki
Also I just update xdph-git and here is the service thing
```sh
[Unit]
Description=Portal service (Hyprland implementation)
PartOf=graphical-session.target
After=graphical-session.target
ConditionEnvironment=WAYLAND_DISPLAY

[Service]
Type=dbus
BusName=org.freedesktop.impl.portal.desktop.hyprland
ExecStart=/usr/lib/xdg-desktop-portal-hyprland
Restart=on-failure
Slice=session.slice
```
but still getting this error
![image](https://github.com/hyprwm/xdg-desktop-portal-hyprland/assets/46407603/96a82210-3bc9-44db-aa45-24d287e46250)

**Comment by salimp2009** [comment]
I also looked at /usr/share/xdg-desktop-portal/ folder and there is hyprland-portals.conf in there too. So it looks like the package is updated but somehow it is failing. it used to work properly before. I was not using the -git package tough but since hyprland-git required hyprcursor and hyprlang newer version, I had to used xdph-git .
