### ISSUE TITLE
Missing dependency libhyprlang.so=0-64

### ISSUE THREAD

**Issue by mylinuxforwork** [hyprwm/xdg-desktop-portal-hyprland#184]
Hi,

Just tried to install xdg-desktop-portal-hyprland with

`sudo pacman -S xdg-desktop-portal-hyprland`

Got the error: unable to satisfy dependeny libhyprlang.so=0-64

Any idea?

Stephan

**Comment by vaxerski** [comment]
Yes. See https://github.com/hyprwm/hyprlang/issues/22

tl;dr: it's arch's fault.

**Comment by mylinuxforwork** [comment]
Thanks. Means waiting for an Arch update that fixes the error?

**Comment by vaxerski** [comment]
si

**Comment by mylinuxforwork** [comment]
Thanks.
