### ISSUE TITLE
GTK4/Libadwaita Apps Not Recieving Colour Scheme

### ISSUE THREAD

**Issue by cprin21** [hyprwm/xdg-desktop-portal-hyprland#186]
Using nwg-look my theme is set to prefer-dark and yet apps like gnome-calendar do not respect this using the git version of xdg-desktop-portal-hyprland.

Waybar when killed and restarted mentions something about dbus being unable to receive desktop appearance, which may be why theming is broken.

```
[2024-02-19 08:40:40.038] [info] Unable to receive desktop appearance: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
```

And here is the output of `gnome-calendar --debug` also mentioning something about "no such interface" in regards to portal settings.

```
08:38:55.147951                       Adwaita:    DEBUG: Portal doesn't provide settings: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
08:38:55.148266                       Adwaita:    DEBUG: Portal doesn't provide settings: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
```

This issue was not present before updating from xdg-desktop-portal-hyprland to xdg-desktop-portal-hyprland-git to update to the latest commit of Hyprland.

**Comment by vaxerski** [comment]
are you maybe missing `xdg-desktop-portal-gtk`?

**Comment by cprin21** [comment]
Not missing `xdg-desktop-portal-gtk`, issue remains with that portal (Installed for file chooser)

**Comment by vaxerski** [comment]
well I believe it's a problem with gtk then because xdph does not povide this portal (and won't)

**Comment by cprin21** [comment]
Understandable, just from a user's perspective, gtk4 theming worked until updating hyprland-git at which point the hyprland-git XDG desktop portal git branch was needed which was when the gtk4 theming broke.

**Comment by cprin21** [comment]
Reinstalling the non-AUR version of xdg-desktop-portal-hyprland works now, does not error with a hyprlang dependency problem like before and GTK4 apps are receiving theming again.
