### ISSUE TITLE
XDPH refuses to start

### ISSUE THREAD

**Issue by alba4k** [hyprwm/xdg-desktop-portal-hyprland#188]
```
× xdg-desktop-portal-hyprland.service - Portal service (Hyprland implementation)
     Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal-hyprland.service; static)
     Active: failed (Result: exit-code) since Mon 2024-02-19 20:16:51 CET; 3min 6s ago
    Process: 1652 ExecStart=/home/alba4k/.cache/paru/clone/xdg-desktop-portal-hyprland-git/pkg/xdg-desktop-portal-hyprland-git/usr/lib/xdg-desktop-portal-hyprland (code=exited, status=203/EXEC)
   Main PID: 1652 (code=exited, status=203/EXEC)
        CPU: 309us

feb 19 20:16:51 dell-xps systemd[1177]: xdg-desktop-portal-hyprland.service: Scheduled restart job, restart counter is at 3.
feb 19 20:16:51 dell-xps systemd[1177]: xdg-desktop-portal-hyprland.service: Start request repeated too quickly.
feb 19 20:16:51 dell-xps systemd[1177]: xdg-desktop-portal-hyprland.service: Failed with result 'exit-code'.
feb 19 20:16:51 dell-xps systemd[1177]: Failed to start Portal service (Hyprland implementation).

```

**Comment by alba4k** [comment]
possibly related to https://github.com/hyprwm/Hyprland/issues/4744 ?

**Comment by vaxerski** [comment]
no

**Comment by alba4k** [comment]
Also, programs like firefox are taking longer than usual to launch. I could also imagine (and could be equally wrong ;) ) that this might be related to a portal not running, as the speed is normal when using the (broken) outdated version

**Comment by vaxerski** [comment]
stacktrace? verbose logs? You provide nothing you get nothing

**Comment by alba4k** [comment]
Yup, here you go

first things first, I was able to get a normal looking recording (without any weird flickering) after https://github.com/hyprwm/Hyprland/issues/4744, and firefox now opens at the usual speed. Thanks :)

Now, as for xdph, it worked as intended when ran manually (`/lib/xdph`) but not when running via systemd

So I thought of looking at the service files, and would you look at that, whoever is maintaining the aur package did a really, really impressive job! this is what I found:

![immagine](https://github.com/hyprwm/xdg-desktop-portal-hyprland/assets/84153269/0519a0f2-be55-4638-807a-33e88cb5dbd7)

I guess I'll try to figure out if that's on me on paru or what, but hey, i guess it works now

still getting some weird graphical glitches at times, and flameshot is often black or showing weird stuff (might be because of flameshot, or something else, ill look into that). sorry for bothering, goodnight.
