### ISSUE TITLE
Trouble getting screen sharing to work

### ISSUE THREAD

**Issue by itmecho** [hyprwm/xdg-desktop-portal-hyprland#19]
Thank you for Hyprland, I've migrated over from `bspwm` and everything has been really simple to setup and use!

The only issue I'm having is that I can't get Firefox to share my screen. I have followed the instructions on the wiki as well as [this guide](https://gist.github.com/PowerBall253/2dea6ddf6974ba4e5d26c3139ffb7580#screen-sharing-on-hyprland-arch-linux) and I still only get the "Use operating system settings" option. Clicking it does nothing.

![image](https://user-images.githubusercontent.com/8384983/216008059-9ac3c0b7-453d-4d2a-a02f-ed58ae7354d6.png)

I think the portal is working as when I try and upload files I get the file picker pop up which if I understand correctly is handled by the portal?

Things I have checked:
- Made sure both `grim` and `slurp` are installed
- Confirmed both `pipewire` and `wireplumber` are running with `systemctl --user status pipewire wireplumber`
- I only have the hyprland xdg-desktop-portal implemetation installed
```
$ pacman -Q | rg xdg-desktop
xdg-desktop-portal 1.16.0-1
xdg-desktop-portal-hyprland-git r250.b03b1c2-1
```
- The desktop portal is running
```
$ ps aux | rg xdg-desktop
iain        1352  0.0  0.1 536848 17624 ?        Ssl  09:20   0:00 /usr/lib/xdg-desktop-portal
iain        1375  0.0  0.2 509096 44496 ?        Ssl  09:20   0:00 /usr/libexec/xdg-desktop-portal-hyprland
```
- Running the `hyprland-share-picker` manually from the terminal works and I can select a screen
![image](https://user-images.githubusercontent.com/8384983/216012641-2525c494-ba20-450f-850a-c1d1614eece1.png)
- I'm on the latest version of the portal: `xdg-desktop-portal-hyprland-git r224.3d3c5a4-2 [+6 ~3.65] [Installed: r250.b03b1c2-1]`
- Firefox is running in wayland mode
![image](https://user-images.githubusercontent.com/8384983/216011062-492c81e7-a45b-46fa-b223-e1bdeccdd76c.png)
- Firefox has the `media.peerconnection.enabled` setting enabled
![image](https://user-images.githubusercontent.com/8384983/216011360-aa44c258-b9a3-4b22-9ab3-ef47ca5fddab.png)
- I have the following line in my `hyprland.conf`
```ini
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
```

I have also tested in chrome and the same thing happens. I can share a tab fine but not a window or screen.

**Comment by vaxerski** [comment]
`systemctl status xdg-desktop-portal-hyprland` please

**Comment by itmecho** [comment]
```
$ systemctl --user status xdg-desktop-portal-hyprland
● xdg-desktop-portal-hyprland.service - Portal service (Hyprland implementation)
     Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal-hyprland.service; static)
     Active: active (running) since Wed 2023-02-01 10:05:43 GMT; 19s ago
   Main PID: 3533 (xdg-desktop-por)
      Tasks: 6 (limit: 19102)
     Memory: 14.5M
        CPU: 34ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/app.slice/xdg-desktop-portal-hyprland.service
             └─3533 /usr/libexec/xdg-desktop-portal-hyprland

Feb 01 10:05:43 orion systemd[1227]: Starting Portal service (Hyprland implementation)...
Feb 01 10:05:43 orion systemd[1227]: Started Portal service (Hyprland implementation).
```

**Comment by itmecho** [comment]
`wireplumber` has some errors/warnings but I'm not sure if they're related to this:
```
$ systemctl --user status wireplumber
● wireplumber.service - Multimedia Service Session Manager
     Loaded: loaded (/usr/lib/systemd/user/wireplumber.service; enabled; preset: enabled)
     Active: active (running) since Wed 2023-02-01 09:55:52 GMT; 11min ago
   Main PID: 2584 (wireplumber)
      Tasks: 5 (limit: 19102)
     Memory: 12.1M
        CPU: 425ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/wireplumber.service
             └─2584 /usr/bin/wireplumber

Feb 01 09:55:52 orion systemd[1227]: Started Multimedia Service Session Manager.
Feb 01 09:55:52 orion wireplumber[2584]: Failed to set scheduler settings: Operation not permitted
Feb 01 09:55:52 orion wireplumber[2584]: [0:01:04.263129421] [2584]  INFO Camera camera_manager.cpp:299 libcamera v0.0.3
Feb 01 09:55:52 orion wireplumber[2584]: The decibel volume range for element 'Mic' (-3000 dB - -100 dB) has negative maximum. Disabling the decibel range.
Feb 01 09:55:53 orion wireplumber[2584]: GetManagedObjects() failed: org.freedesktop.DBus.Error.NameHasNoOwner
Feb 01 09:55:53 orion wireplumber[2584]: <WpPortalPermissionStorePlugin:0x55dce9c90aa0> Failed to call Lookup: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for camera
Feb 01 09:55:53 orion wireplumber[2584]: <WpPortalPermissionStorePlugin:0x55dce9c90aa0> Failed to call Lookup: GDBus.Error:org.freedesktop.portal.Error.NotFound: No entry for camera
```

**Comment by vaxerski** [comment]
open two terminals, A and B
A:
`killall xdg-desktop-portal xdg-desktop-portal-hyprland`
`/usr/lib/xdg-desktop-portal-hyprland -l DEBUG`

B:
`/usr/lib/xdg-desktop-portal`

See if the debug log notes anything out of the ordinary when you try to screenshare. In firefox, try screensharing, click use operating system settings, click allow, and see the logs.

**Comment by itmecho** [comment]
OK it worked when I did that. Killed those again and started them via `systemctl` and it's still working?

Not quite sure what happened there but it seems fine now! Thanks for the debug commands, they'll be useful if it stop working again =]
