### ISSUE TITLE
xdg-desktop-portal-hyprland core dumps, wrong QT version!

### ISSUE THREAD

**Issue by jh-devv** [hyprwm/xdg-desktop-portal-hyprland#194]
```
Cannot mix incompatible Qt library (6.6.2) with this library (6.6.1)
```

I can post the full core dump if needed

This is with Nixos on Hyprland with the flake!

**Comment by jh-devv** [comment]
oh god damm
I was not following nixpkgs!

**Comment by hieulw** [comment]
hey I encountered the same problem when execute `hyprland-share-picker`. Have you solved this ?
```
(hyprland-share-picker:28251): Gtk-WARNING **: 00:18:29.281: Unable to locate theme engine in module_path: "clearlooks",

(hyprland-share-picker:28251): Gtk-WARNING **: 00:18:29.281: Unable to locate theme engine in module_path: "clearlooks",
Cannot mix incompatible Qt library (6.6.1) with this library (6.6.2)
zsh: IOT instruction (core dumped)  hyprland-share-picker
```

**Comment by vaxerski** [comment]
the error is self-explanatory. You compiled the picker for a different qt ver

**Comment by mairm1340** [comment]
May 23 16:31:20 s2600cwr systemd[1]: Created slice Slice /system/systemd-coredump.
May 23 16:31:20 s2600cwr systemd[1]: Started Process Core Dump (PID 3495/UID 0).
May 23 16:31:22 s2600cwr systemd-coredump[3496]: Process 2163 (Hyprland) of user 1000 dumped core.
                                                 
                                                 Stack trace of thread 2163:
                                                 #0  0x000079c80a0a8e44 n/a (libc.so.6 + 0x94e44)
                                                 #1  0x000079c80a050a30 raise (libc.so.6 + 0x3ca30)
                                                 #2  0x000079c80a0384c3 abort (libc.so.6 + 0x244c3)
                                                 #3  0x0000650aae0eaae3 _Z25handleUnrecoverableSignali (Hyprland + 0x160ae3)
                                                 #4  0x000079c80a050ae0 n/a (libc.so.6 + 0x3cae0)
                                                 #5  0x0000650ac0573e60 n/a (n/a + 0x0)
                                                 #6  0x000079c80a53f596 n/a (libffi.so.8 + 0x7596)
                                                 #7  0x000079c80a53c00e n/a (libffi.so.8 + 0x400e)
                                                 #8  0x000079c80a53ebd3 ffi_call (libffi.so.8 + 0x6bd3)
                                                 #9  0x000079c80abc9ada n/a (libwayland-server.so.0 + 0x8ada)
                                                 #10 0x000079c80abce180 n/a (libwayland-server.so.0 + 0xd180)
                                                 #11 0x000079c80abccae2 wl_event_loop_dispatch (libwayland-server.so.0 + 0xbae2)
                                                 #12 0x000079c80abcd2d7 wl_display_run (libwayland-server.so.0 + 0xc2d7)
                                                 #13 0x0000650aae22ab75 _ZN17CEventLoopManager9enterLoopEP10wl_displayP13wl_event_loop (Hyprland + 0x2a0b75)
                                                 #14 0x0000650aae08be1a main (Hyprland + 0x101e1a)
                                                 #15 0x000079c80a039c88 n/a (libc.so.6 + 0x25c88)
                                                 #16 0x000079c80a039d4c __libc_start_main (libc.so.6 + 0x25d4c)
                                                 #17 0x0000650aae0bb265 _start (Hyprland + 0x131265)
                                                 
                                                 Stack trace of thread 2192:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2191:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2168:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c80a2d5e61 __gthread_cond_wait (libstdc++.so.6 + 0xd5e61)
                                                 #3  0x0000650aae1cf008 n/a (Hyprland + 0x245008)
                                                 #4  0x000079c80a2e0c84 execute_native_thread_routine (libstdc++.so.6 + 0xe0c84)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2190:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2193:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2197:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2203:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2184:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2205:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2187:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2201:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2194:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2195:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2200:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2206:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2186:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2202:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2189:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2185:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2204:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2198:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2188:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2208:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2222:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2199:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2209:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2223:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2207:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2196:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2227:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2224:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2225:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2539:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2226:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2483:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 
                                                 Stack trace of thread 2482:
                                                 #0  0x000079c80a0a34e9 n/a (libc.so.6 + 0x8f4e9)
                                                 #1  0x000079c80a0a5ed9 pthread_cond_wait (libc.so.6 + 0x91ed9)
                                                 #2  0x000079c7fde9891e n/a (radeonsi_dri.so + 0x9891e)
                                                 #3  0x000079c7fde766cc n/a (radeonsi_dri.so + 0x766cc)
                                                 #4  0x000079c7fde9884d n/a (radeonsi_dri.so + 0x9884d)
                                                 #5  0x000079c80a0a6ded n/a (libc.so.6 + 0x92ded)
                                                 #6  0x000079c80a12a0dc n/a (libc.so.6 + 0x1160dc)
                                                 ELF object binary architecture: AMD x86-64
May 23 16:31:22 s2600cwr systemd[1]: systemd-coredump@0-3495-0.service: Deactivated successfully.
May 23 16:31:22 s2600cwr systemd[1]: systemd-coredump@0-3495-0.service: Consumed 1.045s CPU time.
May 23 16:31:22 s2600cwr xdg-desktop-por[2402]: Error reading events from display: Broken pipe
May 23 16:31:22 s2600cwr polkitd[2169]: Unregistered Authentication Agent for unix-session:2 (system bus name :1.147, object path /org/gnome/PolicyKit1/AuthenticationAgent, locale en_IN) (disconnected from bus)
May 23 16:31:22 s2600cwr systemd[2113]: xdg-desktop-portal-gtk.service: Main process exited, code=exited, status=1/FAILURE
May 23 16:31:22 s2600cwr systemd[2113]: xdg-desktop-portal-gtk.service: Failed with result 'exit-code'.
May 23 16:31:22 s2600cwr sddm-helper[2103]: [PAM] Closing session
May 23 16:31:22 s2600cwr sddm-helper[2103]: pam_unix(sddm:session): session closed for user amrim
May 23 16:31:22 s2600cwr vmnetBridge[1534]: RTM_NEWLINK: name:eno1 index:2 flags:0x00011043
May 23 16:31:22 s2600cwr vmnet-natd[1727]: RTM_NEWLINK: name:eno1 index:2 flags:0x00011043
May 23 16:31:22 s2600cwr kernel: igb 0000:01:00.0 eno1: left promiscuous mode
May 23 16:31:22 s2600cwr kernel: bridge-eno1: disabled promiscuous mode
May 23 16:31:22 s2600cwr sddm-helper[2103]: [PAM] Ended.
May 23 16:31:22 s2600cwr sddm[1679]: Auth: sddm-helper exited with 134
