### ISSUE TITLE
Support for accent color

### ISSUE THREAD

**Issue by lokesh-krishna** [hyprwm/xdg-desktop-portal-hyprland#200]
Could you please consider adding support for `org.freedesktop.appearance accent-color`?

**Comment by fufexan** [comment]
Is it not already implemented by `xdg-desktop-portal-gtk`?

**Comment by lokesh-krishna** [comment]
Ah, I didn't know that would work. Thanks!

**Comment by lokesh-krishna** [comment]
Any idea on how one can set an accent color? Gsettings doesn't seem to help.

**Comment by Dejweed** [comment]
I would also like to know this. I don't think it's implemented yet.

**Comment by fufexan** [comment]
Looks like it's not implemented in the gtk desktop portal.

**Comment by Dejweed** [comment]
Seems like this isn't fixed. Please reopen if that is the case.
