### ISSUE TITLE
[hyprland / xdph] lower framerate with pipewire screen capture (OBS)

### ISSUE THREAD

**Issue by Fxzzi** [hyprwm/xdg-desktop-portal-hyprland#201]
Here's a [video](https://cdn.discordapp.com/attachments/980082845831823420/1219366267669057787/2024-03-18_19-25-41.mp4?ex=660b0a54&is=65f89554&hm=dd8683ad8a1ff86242a24c36323b950e04baf2c3f827eba9f29ad22765d4d40d&) to showcase what I'm experiencing.

The `dmabuf` capture is coming from the [wlrobs](https://hg.sr.ht/~scoopta/wlrobs) plugin. I installed it via `wlrobs-hg` on the AUR.

If you can tell, the dmabuf capture on the left looks much smoother than the pipewire screen cap on the right. I have no idea if this is related to xdph, hyprland, or novideo, but I am posting here as I assume the screen cap source comes from xdph.

It seems the wlrobs plugin might have had a similar issue: https://todo.sr.ht/~scoopta/wlrobs/23
No idea if these are related somehow, I know nothing about how this schtuff works.

Let me know if you can repro this, or if this is the wrong place to post.

**Comment by Fxzzi** [comment]
After further testing, I have ruled out it being an issue with Nvidia. The same occurs on my laptop which is amd based with an amd igpu.

https://github.com/hyprwm/xdg-desktop-portal-hyprland/assets/18248986/e189420f-48cd-4d0f-8982-70bd74345834

May be hard to tell here, but the pipewire capture (xdph) definitely has a more laggy cursor than dmabuf. (pipewire is bottom right)

I can tell even from the OBS preview that the mouse isn't as smooth. This isn't just mouse cursor issue, its an issue over the entire capture. Occurs with both hw and sw cursors, amd and nvidia igpus.

**Comment by vaxerski** [comment]
#120
