### ISSUE TITLE
terminate called after throwing an instance of 'char const*'

### ISSUE THREAD

**Issue by akohlen** [hyprwm/xdg-desktop-portal-hyprland#205]
Distro: Arch Linux
hyprlang 0.5.0-1
xdg-desktop-portal-hyprland-git 1.3.1.r14.g2d2fb547-1

It worked for the last year but suddenly after updates this week when running  `/usr/lib/xdg-desktop-portal-hyprland` I'm getting
> /usr/lib/xdg-desktop-portal-hyprland: error while loading shared libraries: libhyprlang.so.1: cannot open shared object file: No such file or directory

I followed [Problem with libhyprlang.so.1] (https://www.reddit.com/r/hyprland/comments/1bjiue7/problem_with_libhyprlangso1/) and linked 

`sudo ln -sf /usr/lib64/libhyprlang.so.0.5.0 /usr/lib64/libhyprlang.so.1 `

now I'm getting `journalctl --user -xeu xdg-desktop-portal-hyprland.service`

> systemd[293659]: Starting Portal service (Hyprland implementation)...
> ░░ Subject: A start job for unit UNIT has begun execution
> ░░ Defined-By: systemd
> ░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
> ░░ 
> ░░ A start job for unit UNIT has begun execution.
> ░░ 
> ░░ The job identifier is 1560.
> xdg-desktop-portal-hyprland[815641]: terminate called after throwing an instance of 'char const*'
> systemd-coredump[815643]: [🡕] Process 815641 (xdg-desktop-por) of user 11601 dumped core.
>                                                    
>                                                    Stack trace of thread 815641:
>                                                    #0  0x00007067dc4ab32c n/a (libc.so.6 + 0x8d32c)
>                                                    #1  0x00007067dc45a6c8 raise (libc.so.6 + 0x3c6c8)
>                                                    #2  0x00007067dc4424b8 abort (libc.so.6 + 0x244b8)
>                                                    #3  0x00007067dc69ca6f _ZN9__gnu_cxx27__verbose_terminate_handlerEv (libstdc++.so.6 + 0x9ca6f)
>                                                    #4  0x00007067dc6b011c _ZN10__cxxabiv111__terminateEPFvvE (libstdc++.so.6 + 0xb011c)
>                                                    #5  0x00007067dc6b0189 _ZSt9terminatev (libstdc++.so.6 + 0xb0189)
>                                                    #6  0x00007067dc6b03ed __cxa_throw (libstdc++.so.6 + 0xb03ed)
>                                                    #7  0x00007067dc9f606a n/a (libhyprlang.so.1 + 0xc06a)
>                                                    #8  0x0000649c1b648b22 n/a (xdg-desktop-portal-hyprland + 0x11b22)
>                                                    #9  0x0000649c1b646825 n/a (xdg-desktop-portal-hyprland + 0xf825)
>                                                    #10 0x00007067dc443cd0 n/a (libc.so.6 + 0x25cd0)
>                                                    #11 0x00007067dc443d8a __libc_start_main (libc.so.6 + 0x25d8a)
>                                                    #12 0x0000649c1b647815 n/a (xdg-desktop-portal-hyprland + 0x10815)
>                                                    ELF object binary architecture: AMD x86-64
> ░░ Subject: Process 815641 (xdg-desktop-por) dumped core
> ░░ Defined-By: systemd
> ░░ Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
> ░░ Documentation: man:core(5)
> ░░ 
> ░░ Process 815641 (xdg-desktop-por) crashed and dumped core.
> ░░ 
> ░░ This usually indicates a programming error in the crashing program and
> ░░ should be reported to its vendor as a bug.

Any idea how I could fix this?

**Comment by vaxerski** [comment]
> I followed [Problem with libhyprlang.so.1] (https://www.reddit.com/r/hyprland/comments/1bjiue7/problem_with_libhyprlangso1/) and linked

> sudo ln -sf /usr/lib64/libhyprlang.so.0.5.0 /usr/lib64/libhyprlang.so.1 

Please don't listen to idiots online, this is terrible advice.

just recompile xdph.
