### ISSUE TITLE
File Dialog is not working in flatpaks

### ISSUE THREAD

**Issue by PucklaJ** [hyprwm/xdg-desktop-portal-hyprland#221]
When I started using the Heroic Games Launcher as a flatpak I noticed that every time it wants to open a file dialog it does not work and the application even hangs. In Waterfox when using the flatpak also no file dialog can be opened (e.g. when downloading a file). If it is a dialog for folders then it works. I tested it under Plasma and it opens a file dialog. Therefore I assumed that it is an issue concerning the portal of hyprland.

## System Specs
+ Arch Linux x86_64 (linux 6.9.1-arch1-2)
+ Hyprland (built from branch  at commit cba1ade848feac44b2eda677503900639581c3f4  (props: bump version to 0.40.0).
+ xdg-desktop-portal-hyprland (arch package 1.3.1-6)

**Comment by vaxerski** [comment]
xdph does not provide a file picker. You need another portal alongside, e.g. gtk
