### ISSUE TITLE
segfault after random interval between 1s - 6 minutes of screen sharing OR recording with OBS

### ISSUE THREAD

**Issue by alexlnkp** [hyprwm/xdg-desktop-portal-hyprland#222]
This issue has existed on my system, then it vanished, and then it appeared again, not sure what's the cause, but it's not NVIDIA GPU which I'm using, since between this issue not existing and then it re-appearing i didn't change anything related to NVIDIA on my system.

Here's journalctl and dmesg: [jctl-xdg-segv.log](https://github.com/user-attachments/files/15615216/jctl-xdg-segv.log)
													 [dmesg-xdg-segv.log](https://github.com/user-attachments/files/15615211/dmesg-xdg-segv.log)

I thought about sending the coredumps too, but I'm not entirely sure if it would be a good idea for security purposes, although I might be wrong. 

The stack trace looks like garbage, I assume it is because of the absence of debug symbols. I could run Hyprland with `gdb` but i'm not sure how loading multiple symbol-files from *-debug packages would work?

Please let me know if i need to provide more information, this issue is just so bizzare to me...

**Comment by DADA30000** [comment]
wow, 3 months old

**Comment by alexlnkp** [comment]
> wow, 3 months old

To be entirely honest, I kind of forgot I even opened this issue.
I think that in the end the problems were caused by NVIDIA drivers, though, as now it's all seemingly fixed. So I'll be closing this issue.
