### ISSUE TITLE
[Bug] Custom cursors ignored in share region picker

### ISSUE THREAD

**Issue by 00-kat** [hyprwm/xdg-desktop-portal-hyprland#224]
If you use the "select region" thing in the dialog that pops up when you open OBS, or if an app like Pinta asks for a screenshot, Adwaita cursors at a very small size are used, rather than the Hyprcursor I have set. I don't know if the problem exists with X cursors too. Furthermore, the cursor size becomes a bit finicky afterwards until the session is restarted.

I wish I could demonstrate with a screenshot, but the cursor hides if slurp opens.

**Comment by vaxerski** [comment]
https://wiki.hyprland.org/FAQ/#how-do-i-change-me-mouse-cursor

**Comment by 00-kat** [comment]
Oh hadn't realised that the instructions to set the cursor had changed. However, that changed nothing. Also worth noting that the share picker thing is the only app that doesn't respect the cursor.

**Comment by vaxerski** [comment]
is the picker running in xwayland?

**Comment by 00-kat** [comment]
I only just got to trying it out but:

`env = HYPRCURSOR_THEME` does nothing
`exec-once = hyprctl setcursor` does nothing
Both at once do nothing
I checked the Hyprland logs, and always saw a line that was something about reading the Hyprcursor from an environment variable...

The only thing that worked for me was changing the fallback theme in `/usr/share/icons/default/index.theme` from a Hyprcursor to an X cursor.

As for whether it's running in XWayland, I don't know. `hyprctl clients` doesn't show it, and `hyprctl layers` shows it but it doesn't say anything about XWayland. `pgrep xwayland` from a TTY doesn't return anything though.

**Comment by vaxerski** [comment]
the screensharing picker is not a layer, are you using xdph?

**Comment by 00-kat** [comment]
> the screensharing picker is not a layer

IDK it showed up in `hyprctl layers`, lemme try again.

> are you using xdph?

Yes, I'm 100% sure.

**Comment by vaxerski** [comment]
the selection layer is slurp. Slurp uses XCURSOR_SIZE and XCURSOR_THEME to render a cursor. If that has an invalid cursor, those two are wrong.

**Comment by 00-kat** [comment]
> the selection layer is slurp. ... If that has an invalid cursor, those two are wrong.

Okay I think I found the bug. If I comment out everything in `/usr/share/icons/default/index.theme` then run `XCURSOR_THEME= slurp` I get that same cursor. So my guess now is that `XCURSOR_THEME` isn't being passed to the slurp process by XDPH.
