### ISSUE TITLE
Can't hide the share screen notification

### ISSUE THREAD

**Issue by goldyfruit** [hyprwm/xdg-desktop-portal-hyprland#234]
When sharing I got the usual notification but I can't hide it.

![image](https://github.com/hyprwm/xdg-desktop-portal-hyprland/assets/614115/88776d59-a003-48bd-8d5a-d7d7b1b40572)

Is there a way to make it disappear when clicking on "Hide"? For now the workaround is to move it to a different workspace.

Thanks :+1:

**Comment by vaxerski** [comment]
that's a window that chromium itself opens. IIRC you can disable it in chromium's flags or something.

**Comment by goldyfruit** [comment]
@vaxerski I was looking for this option before opening this issue but I didn't find anything about it in Chrome/Chromium.

**Comment by vaxerski** [comment]
that's why I said IIRC. I've heard somewhere that you can disable that.
