### ISSUE TITLE
OBS Freezes on Wayland with Pipewire (xdg-desktop-portal-hyprland)

### ISSUE THREAD

**Issue by different-name** [hyprwm/xdg-desktop-portal-hyprland#239]
## OS

Arch
NixOS

## Behaviour

OBS Screen Capture (pipewire) freezes as soon as the input is selected

https://github.com/user-attachments/assets/435758a5-a0ba-4d07-aa6d-f3d8c04b383f

See original OBS issue where this was marked as a xdg-desktop-portal-hyprland issue:
https://github.com/obsproject/obs-studio/issues/10959

**Comment by dec05eba** [comment]
I cant reproduce this. Are you using latest hyprland installed from master branch?

**Comment by Different-Name** [comment]
They've just merged the swap to aquamarine into master I believe so likely a lot of big changes, will try reproduce tomorrow and update

**Comment by Different-Name** [comment]
> I cant reproduce this. Are you using latest hyprland desktop portal and hyprland installed from master branch?

I am using the latest commit on the master branch of xdg-desktop-portal hyprland, and this commit from 7 hours ago on hyprland https://github.com/hyprwm/Hyprland/commit/cbaac6deafb857662d630efbca8b0ebac0f11b44

Able to reproduce reliably, might be noteworthy that I am on an Nvidia card, and I've looked through the logs attached in the original issue, they are also using an Nvidia card

First launch can be okay, with the source not freezing, seems to reliably break on subsequent launches and after clicking the `Select Monitor` button in the source properties

**Comment by dec05eba** [comment]
Oh ok that might explain it then, I tested it on amd

**Comment by SSS-Says-Snek** [comment]
I can reproduce the issue (I also have an Nvidia card)

**Comment by Oery** [comment]
I can reproduce it and I'm on Nvidia and latest commit. The stream freeezes instantly when created on OBS first, but if a stream is created on Discord, then the OBS streams works fine. There are no errors nor warnings in my logs.

**Comment by mufaroxyz** [comment]
Any updates on this? I'm still having issues on Nvidia

**Comment by sfjuocekr** [comment]
I have the same-ish issue, the funny thing is when I have OBS active it captures fine but when I switch back to the game my game output freezes!

When I tab back to OBS the game seems to continue fine in the background.

**Comment by mufaroxyz** [comment]
So far the only workaround I found that worked for me is: 
https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/220#issuecomment-2227471077

**Comment by different-name** [comment]
I'm going to close this issue since I can no longer reproduce, perhaps it was fixed accidentally :partying_face: 
If anyone else is still experiencing this I'm happy to reopen
