### ISSUE TITLE
Black screen when screen sharing in some programs

### ISSUE THREAD

**Issue by alba4k** [hyprwm/xdg-desktop-portal-hyprland#247]
When starting a screen share from firefox or from obs (recording), everything is fine.
However, telegram desktop and discord (vesktop) both just get a black screen

![immagine](https://github.com/user-attachments/assets/72d64124-f15e-4b22-9758-0ccb9fe2c2a4)

[xdph.txt](https://github.com/user-attachments/files/16580521/xdph.txt)

All I did here was start and stop a screenshare on vesktop (which, as you likely already know, requires the user to interact with the portal window 3 times for some reason, 1 for the preview and 2 for the screenshare)

**Comment by juanfranUam** [comment]
I had this problem too, i had to use the xdg-desktop-portal-wlr instead until they fix this bug, screen sharing. It's been a pain to get screen sharing working reliably on Linux

**Comment by alba4k** [comment]
@lennoxlotl suggested this on the discord:

> I recently noticed some people having issues with XDPH and screensharing the entire screen (not an application) on Vesktop. I also recently switched back to Hyprland and noticed the same issue so I thought I will just try random bullshit to see if I can get a hacky fix working. (It might be worth noting that this only happens on certain resolution and fps combinations, for me anything thats low fps and low resolution works, 1440p@60fps doesn't though)
It seems like the issue is an Out of buffers error which results in no future frame captures even being started afterwards. After a bit of trying around I just manually re-queued the next frame and it seems to work now. If anybody else has the same issue, I guess you can temporarily fix it by inserting 2 lines of code until someone smarter than me fixes it properly.
> 
> Yes I know this is not a real fix as it doesn't get rid of the Out of buffers error, it only works around it. I never worked with portals or pipewire or anything even related to that so the code below is just the first thing that came into my mind, it is located in Screencopy.cpp.
> 
> ![immagine](https://github.com/user-attachments/assets/d2b81a2f-964c-47f5-8216-3fdcf27307e0)

**Comment by alba4k** [comment]
@vaxerski as you required a bisect in https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/248#issuecomment-2286789306

The first commit that I managed to build (as the other fail because wlroots-hyprland is missing) is https://github.com/hyprwm/Hyprland/commit/016da234d0e852de3ef20eb2e89ac58d2a85f6e7, and the issue is there in that one too.

**Comment by vaxerski** [comment]
can you make a MR then so we can discuss in a real place with the code

**Comment by lennoxlotl** [comment]
i can make a pr with this in a 2-3 hours once im home

**Comment by lennoxlotl** [comment]
made a draft mr for further discussion

**Comment by shogeki** [comment]
I was having this issue as described above before this merge, but with the merge the second window does not even pop up with the preview, instead it just breaks discord and will not attempt to stream again when the button is clicked until the client is restarted.  Still works in OBS.

**Comment by lennoxlotl** [comment]
Can you send logs?

**Comment by shogeki** [comment]
bitdepth,8 gets me sorted.

**Comment by lennoxlotl** [comment]
Interesting, might be a Vesktop only thing then /shrug.

**Comment by alba4k** [comment]
Telegram desktop has that issue too

**Comment by lennoxlotl** [comment]
> Telegram desktop has that issue too

The bitdepth one? If yes logs would still be good to see whats going on

**Comment by goldyfruit** [comment]
@alba4k are you able to screenshare?

**Comment by alba4k** [comment]
I broke my laptop by spilling on it a week ago. 

Just got home, put the battery back in and it works now, but I will check tomorrow and let you know as I'm going to bed

**Comment by alba4k** [comment]
While the preview sometimes is still black in vesktop (probably because it only asks for 1 frame, meaning that the retry is meaningless?) the screen share is working alright. Not sure if I should close?

**Comment by goldyfruit** [comment]
Still not working for me :/

**Comment by goldyfruit** [comment]
Recompiled and reboot worked :/

**Comment by piyushyadav0191** [comment]
@goldyfruit @alba4k I am able to screen share in small region but when i screenshare entire screen then nothing happens. You know the solution?

My logs 

```
xdg-desktop-portal.service - Portal service
     Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal.service; static)
     Active: active (running) since Wed 2024-08-28 16:28:18 IST; 10min ago
 Invocation: 3b4c3113ab0a4d598593c3502969f01d
   Main PID: 10772 (xdg-desktop-por)
      Tasks: 5 (limit: 7014)
     Memory: 3.6M (peak: 4.4M)
        CPU: 206ms
     CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/xdg-desktop-portal.service
             └─10772 /usr/lib/xdg-desktop-portal

Aug 28 16:28:18 laptop xdg-desktop-por[10772]: Choosing gtk.portal for org.freedesktop.impl.portal.Notification as a last-resort fallback
Aug 28 16:28:18 laptop xdg-desktop-por[10772]: Choosing gtk.portal for org.freedesktop.impl.portal.Inhibit as a last-resort fallback
Aug 28 16:28:18 laptop xdg-desktop-por[10772]: Choosing gtk.portal for org.freedesktop.impl.portal.Access as a last-resort fallback
Aug 28 16:28:18 laptop xdg-desktop-por[10772]: Choosing hyprland.portal for org.freedesktop.impl.portal.Screenshot via the deprecated UseIn key
Aug 28 16:28:18 laptop xdg-desktop-por[10772]: Choosing gtk.portal for org.freedesktop.impl.portal.Account as a last-resort fallback
Aug 28 16:28:18 laptop xdg-desktop-por[10772]: Choosing gtk.portal for org.freedesktop.impl.portal.Email as a last-resort fallback
Aug 28 16:28:18 laptop xdg-desktop-por[10772]: Choosing hyprland.portal for org.freedesktop.impl.portal.GlobalShortcuts via the deprecated UseIn key
Aug 28 16:28:18 laptop xdg-desktop-por[10772]: Choosing gtk.portal for org.freedesktop.impl.portal.DynamicLauncher as a last-resort fallback
Aug 28 16:28:18 laptop xdg-desktop-por[10772]: Choosing hyprland.portal for org.freedesktop.impl.portal.ScreenCast via the deprecated UseIn key
Aug 28 16:28:18 laptop systemd[652]: Started Portal service.

● xdg-desktop-portal-hyprland.service - Portal service (Hyprland implementation)
     Loaded: loaded (/usr/lib/systemd/user/xdg-desktop-portal-hyprland.service; static)
     Active: active (running) since Wed 2024-08-28 16:28:18 IST; 10min ago
 Invocation: 5b22c1dd7f6e4b35887d13d7a0a9a702
   Main PID: 10755 (xdg-desktop-por)
      Tasks: 9 (limit: 7014)
     Memory: 8.6M (peak: 38.6M)
        CPU: 7.470s
     CGroup: /user.slice/user-1000.slice/user@1000.service/session.slice/xdg-desktop-portal-hyprland.service
             └─10755 /usr/lib/xdg-desktop-portal-hyprland

Aug 28 16:36:01 laptop xdg-desktop-portal-hyprland[10755]: [LOG] [screencopy]  | /org/freedesktop/portal/desktop/session/1_54/webrtc_session1091435865
Aug 28 16:36:01 laptop xdg-desktop-portal-hyprland[10755]: [LOG] [screencopy]  | appid:
Aug 28 16:36:01 laptop xdg-desktop-portal-hyprland[10755]: [LOG] [screencopy] option persist_mode to 1
Aug 28 16:36:01 laptop xdg-desktop-portal-hyprland[10755]: [LOG] [screencopy] unused option multiple
Aug 28 16:36:01 laptop xdg-desktop-portal-hyprland[10755]: [LOG] [screencopy] unused option types
Aug 28 16:36:01 laptop xdg-desktop-portal-hyprland[10755]: [LOG] [screencopy] restore data invalid / missing, prompting
```

**Comment by alba4k** [comment]
@piyushyadav0191 are you on git already?
