### ISSUE TITLE
Screensharing is not working (Google meet) on any browser 

### ISSUE THREAD

**Issue by piyushyadav0191** [hyprwm/xdg-desktop-portal-hyprland#250]
My screen sharing used to work in hyprland but it's not working now even added bitdepth,10 to monitor and followed https://gist.github.com/brunoanc/2dea6ddf6974ba4e5d26c3139ffb7580 but not working. Please help

**Comment by vaxerski** [comment]
please don't open duplicate issues https://github.com/hyprwm/Hyprland/issues/7447
