### ISSUE TITLE
Suggestion: Allow restore token by default config option

### ISSUE THREAD

**Issue by 23andreas** [hyprwm/xdg-desktop-portal-hyprland#258]
I often use screen sharing and always select the "allow restore token" option. However, sometimes I forget to enable it, which leads to multiple prompts—especially annoying when there are many windows open.

What's the reasoning for not making "allow restore token" default behavior? If there are any security concerns, could we have a config option to enable it by default?

Thanks!

**Comment by matejdro** [comment]
How to set this config option? I don't see anything regarding config in the README

**Comment by Gliczy** [comment]
https://wiki.hyprland.org/Hypr-Ecosystem/xdg-desktop-portal-hyprland/#configuration

**Comment by matejdro** [comment]
Thank you. README seems to point to a similar page where configuration is missing (https://wiki.hyprland.org/Useful-Utilities/xdg-desktop-portal-hyprland/)

**Comment by vaxerski** [comment]
fixed link
