### ISSUE TITLE
Collaboration with xdpw

### ISSUE THREAD

**Issue by columbarius** [hyprwm/xdg-desktop-portal-hyprland#26]
Hi, I'm one of the xdpw developers and started implementing the parts required for [session restore](https://github.com/emersion/xdg-desktop-portal-wlr/pull/179) and different [capture targets](https://github.com/emersion/xdg-desktop-portal-wlr/commit/1afb71fbae060506a9b73fbf7bd4800161d84cc2). My next goals would be to push those into the chooser part such that users could interact with them.

Would there be interest to collaborate on this task?

Note: tried to join your discord server, but it requires phone validation.

**Comment by vaxerski** [comment]
> Note: tried to join your discord server, but it requires phone validation.

![image](https://user-images.githubusercontent.com/43317083/220174515-7f747139-b17b-45df-9bfe-13f67d78fe14.png)

> Would there be interest to collaborate on this task?

What do you mean by "collaborate"? I maintain `-hyprland` because [hyprland-protocols](https://github.com/hyprwm/hyprland-protocols)

**Comment by vaxerski** [comment]
Hyprland's QT chooser has nothing that would _not_ work with xdpw. Obviously though, sharing windows would not be possible.

Unless you mean making the output whatever xdpw accepts, in which case it's not possible without modifications on the xdpw side.

> Would you be interested in reviewing and/or giving feedback on the capture_target and an improved chooser design (using json to communicate)

I am not sure I understand what that entails. You want _me_ to review your PRs to xdpw? I mean sure, I can. I guess.

> and maybe adapting your chooser, such that it could work with xdpw as well? I'd continue to work on them tomorrow and could link those MRs here.

If you mean making the hyprland chooser use json as output, yeah, sure, that's not a biggie.

**Comment by mesmerx** [comment]
i am working with the same feature @columbarius  you are already in discord?
i get the session restore to work with both window and output, but i need to refactor to work with tiles and not only ids for windows to keep the share working even if the window is closed, if you wanna we can work togther

**Comment by mesmerx** [comment]
i am translating your pr to this portal ( and you id a great job i need to say)

**Comment by columbarius** [comment]
> If you mean making the hyprland chooser use json as output, yeah, sure, that's not a biggie.

Great! I've updated https://github.com/emersion/xdg-desktop-portal-wlr/pull/228.
Please take a look at [chooser-protocol.json](https://github.com/emersion/xdg-desktop-portal-wlr/blob/71b50679030bf04e0efae29ced0de575a7cec4e8/chooser-protocol.json)

**Comment by vaxerski** [comment]
> Yes, but without phone verification I can't write anything there

you can, it's clearly stated in #rules to dm me on discord in case you can't/don't want to verify your phone number.

**Comment by vaxerski** [comment]
I think this can be closed as this is no longer a fork
