### ISSUE TITLE
Wrong window captured when screensharing

### ISSUE THREAD

**Issue by diniamo** [hyprwm/xdg-desktop-portal-hyprland#262]
After bisecting, eb3f3d9854a1222a92b7ae46ff78e8b703cf4452 is the first bad commit.

The issue itself is simple enough: a different window is captured from what I select. From what I can tell, the captured window is always the one that appears first in the selection list.

**Comment by shogeki** [comment]
I still don't think this is entirely working as intended, for example a scenario with multiple Librewolf windows seems to select the first one only.

**Comment by shogeki** [comment]
region picker also doesn't seem to work (selects the whole window no matter what), and background windows only stream at 1fps, not sure if those are related to this issue.

**Comment by diniamo** [comment]
Both of those things seem to work for me.

**Comment by shogeki** [comment]
I tested in OBS and it works as expected.  In vencord removing the tick in restore token also works.  With the restore token in vencord it shows the correct window in the preview but goes on to stream the wrong one.

**Comment by diniamo** [comment]
What does the restore token do normally?

**Comment by shogeki** [comment]
Vencord creates 3 total picker windows to choose what to stream, one after another, but only in the 3rd pop-up what you pick selects what it will actually stream.  Restore token is supposed to reuse the first pick and not show the other 2 pop-ups.

**Comment by diniamo** [comment]
Huh nice, I'll test that and we can open another issues if vaxry doesn't see this.

**Comment by vaxerski** [comment]
right, restore tokens no longer "remember" which instance of an app was shared.
