### ISSUE TITLE
Restore tokens don't preserve the exact window in case of popups

### ISSUE THREAD

**Issue by diniamo** [hyprwm/xdg-desktop-portal-hyprland#264]
The title is self-explanatory. What ends up happening instead, is that the main window is shared. For example, this can happen in libreoffice.

Ref https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/262#issuecomment-2367309289 and https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/262#issuecomment-2368469129

**Comment by vaxerski** [comment]
worth noting if you close the selected window it will restore the main one.

**Comment by diniamo** [comment]
Sounds sensible

**Comment by diniamo** [comment]
I can confirm, the fix for this issue works, however region select is still broken with session restore.

Also is it possible to enable session restore by default? That would be very handy.

**Comment by shogeki** [comment]
you can do that in ~/.config/hypr/xdph.conf
`screencopy {
allow_token_by_default = true
}
`

**Comment by diniamo** [comment]
Where is that documented?
