### ISSUE TITLE
Tearing when sharing screen in Discord/OBS/Etc

### ISSUE THREAD

**Issue by Elibrio** [hyprwm/xdg-desktop-portal-hyprland#265]
When sharing screen through xdg-desktop-portal-wlr/xdg-desktop-portal-hyprland:
Sometimes it works just perfect without any tearing, but most of the time it randomly starts to cut of parts (tearing)

Does anyone have the same problem or knows how to fix it?

Im on Nvidia 560 btw

**Comment by akyoto** [comment]
> most of the time

In my case the problem is 100% reproducible (Nvidia 560).

**Comment by nnra6864** [comment]
Can confirm with latest nvidia 560.

**Comment by Elibrio** [comment]
People who also have Nvidia drivers but only with a single monitor don't have the problem, as far as I've seen

**Comment by nnra6864** [comment]
> People who also have Nvidia drivers but only with a single monitor don't have the problem, as far as I've seen

I have a single monitor, a bit of a weird resolution tho.
5120x1440@240

**Comment by nnra6864** [comment]
I am positive this issue has resolved on it's own for me after updating(although I also switched to 8 bitdepth because of #270) but I have to do some more testing.
I did a short recording with both 8 and 10 bitdepth and it seemed fine.

**Comment by enderprism** [comment]
i disabled explicit_sync because having it enabled spreads the problem to every game window i open

**Comment by Elibrio** [comment]
I have tested it with and without explicit sync, no matter what I have selected, the problem remains

**Comment by Elibrio** [comment]
For me it was finally fixed by explicit_sync=1 (#295), no idea why. You can still see something in the stream, but I hope the future drivers will fix it soon.
