### ISSUE TITLE
Region select captures entire workspace with session restore

### ISSUE THREAD

**Issue by diniamo** [hyprwm/xdg-desktop-portal-hyprland#266]
Selecting a region with session restore enabled discards the region, capturing the workspace the region was on instead.

Ref https://github.com/hyprwm/xdg-desktop-portal-hyprland/issues/264#issuecomment-2368975594

**Comment by vaxerski** [comment]
eee aaa e a e jejejeeee #44

**Comment by diniamo** [comment]
Whoopsies
