### ISSUE TITLE
Failed to emerge xdg-desktop-portal-hyprland 

### ISSUE THREAD

**Issue by EssenSea** [hyprwm/xdg-desktop-portal-hyprland#269]
Here are message. Seems like relative to screenshot.cpp.o 

[32/34] /usr/lib/ccache/bin/x86_64-pc-linux-gnu-g++  -I/var/tmp/portage/gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2/work/xdg-desktop-portal-hyprland-1.3.3/. -I/var/tmp/portage/gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2/work/xdg-desktop-portal-hyprland-1.3.3/protocols -isystem /usr/lib64/libffi/include -isystem /usr/include/pipewire-0.3 -isystem /usr/include/spa-0.2 -isystem /usr/include/libdrm  -march=native -O2 -pipe -std=gnu++23 -Wall -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-missing-field-initializers -Wno-narrowing -Wno-pointer-arith -fpermissive -Wno-address-of-temporary -D_REENTRANT -MD -MT CMakeFiles/xdg-desktop-portal-hyprland.dir/src/portals/Screenshot.cpp.o -MF CMakeFiles/xdg-desktop-portal-hyprland.dir/src/portals/Screenshot.cpp.o.d -o CMakeFiles/xdg-desktop-portal-hyprland.dir/src/portals/Screenshot.cpp.o -c /var/tmp/portage/gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2/work/xdg-desktop-portal-hyprland-1.3.3/src/portals/Screenshot.cpp
FAILED: CMakeFiles/xdg-desktop-portal-hyprland.dir/src/portals/Screenshot.cpp.o 
/usr/lib/ccache/bin/x86_64-pc-linux-gnu-g++  -I/var/tmp/portage/gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2/work/xdg-desktop-portal-hyprland-1.3.3/. -I/var/tmp/portage/gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2/work/xdg-desktop-portal-hyprland-1.3.3/protocols -isystem /usr/lib64/libffi/include -isystem /usr/include/pipewire-0.3 -isystem /usr/include/spa-0.2 -isystem /usr/include/libdrm  -march=native -O2 -pipe -std=gnu++23 -Wall -Wextra -Wno-unused-parameter -Wno-unused-value -Wno-missing-field-initializers -Wno-narrowing -Wno-pointer-arith -fpermissive -Wno-address-of-temporary -D_REENTRANT -MD -MT CMakeFiles/xdg-desktop-portal-hyprland.dir/src/portals/Screenshot.cpp.o -MF CMakeFiles/xdg-desktop-portal-hyprland.dir/src/portals/Screenshot.cpp.o.d -o CMakeFiles/xdg-desktop-portal-hyprland.dir/src/portals/Screenshot.cpp.o -c /var/tmp/portage/gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2/work/xdg-desktop-portal-hyprland-1.3.3/src/portals/Screenshot.cpp
/var/tmp/portage/gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2/work/xdg-desktop-portal-hyprland-1.3.3/src/portals/Screenshot.cpp: In function ‘void pickHyprPicker(sdbus::MethodCall&)’:
/var/tmp/portage/gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2/work/xdg-desktop-portal-hyprland-1.3.3/src/portals/Screenshot.cpp:44:81: error: class template argument deduction failed:
   44 |     results["color"] = sdbus::Struct(std::tuple{r / 255.0, g / 255.0, b / 255.0});
      |                                                                                 ^
/var/tmp/portage/gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2/work/xdg-desktop-portal-hyprland-1.3.3/src/portals/Screenshot.cpp:44:81: error: call of overloaded ‘Struct(std::tuple<double, double, double>)’ is ambiguous
In file included from /usr/include/sdbus-c++/ConvenienceApiClasses.h:32,
                 from /usr/include/sdbus-c++/IObject.h:30,
                 from /usr/include/sdbus-c++/sdbus-c++.h:28,
                 from /var/tmp/portage/gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2/work/xdg-desktop-portal-hyprland-1.3.3/src/portals/Screenshot.hpp:3,
                 from /var/tmp/portage/gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2/work/xdg-desktop-portal-hyprland-1.3.3/src/portals/Screenshot.cpp:1:
/usr/include/sdbus-c++/Types.h:123:18: note: candidate: ‘Struct(const std::tuple<_Ts ...>&)-> sdbus::Struct<_ValueTypes> [with _ValueTypes = {double, double, double}]’
  123 |         explicit Struct(const std::tuple<_ValueTypes...>& t)
      |                  ^~~~~~
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/uses_allocator_args.h:39,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/memory_resource.h:41,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/string:68,
                 from /usr/include/sdbus-c++/TypeTraits.h:31,
                 from /usr/include/sdbus-c++/IConnection.h:30,
                 from /usr/include/sdbus-c++/sdbus-c++.h:27:
/usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/tuple:1970:5: note: candidate: ‘std::Struct(_Ts ...)-> sdbus::Struct<_ValueTypes ...> [with _ValueTypes = {tuple<double, double, double>}]’
 1970 |     tuple(_UTypes...) -> tuple<_UTypes...>;
      |     ^~~~~
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/stl_algobase.h:64,
                 from /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/string:51:
/usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/stl_pair.h:92:11: note: candidate: ‘Struct(std::tuple<_Ts ...>)-> sdbus::Struct<_ValueTypes ...> [with _ValueTypes = {double, double, double}]’
   92 |     class tuple;
      |           ^~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/tuple:993:17: note: candidate: ‘Struct(const std::tuple<_Ts ...>&)-> sdbus::Struct<_ValueTypes ...> [with _ValueTypes = {double, double, double}]’
  993 |       constexpr tuple(const tuple&) = default;
      |                 ^~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/tuple:995:17: note: candidate: ‘Struct(std::tuple<_Ts ...>&&)-> sdbus::Struct<_ValueTypes ...> [with _ValueTypes = {double, double, double}]’
  995 |       constexpr tuple(tuple&&) = default;
      |                 ^~~~~
/usr/include/sdbus-c++/Types.h:143:5: note: candidate: ‘sdbus::Struct(_Elements ...)-> Struct<_ValueTypes ...> [with _Elements = {std::tuple<double, double, double>}]’
  143 |     Struct(_Elements...) -> Struct<_Elements...>;
      |     ^~~~~~
/var/tmp/portage/gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2/work/xdg-desktop-portal-hyprland-1.3.3/src/portals/Screenshot.cpp: In function ‘void pickSlurp(sdbus::MethodCall&)’:
/var/tmp/portage/gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2/work/xdg-desktop-portal-hyprland-1.3.3/src/portals/Screenshot.cpp:94:61: error: class template argument deduction failed:
   94 |         results["color"] = sdbus::Struct(std::tuple{r, g, b});
      |                                                             ^
/var/tmp/portage/gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2/work/xdg-desktop-portal-hyprland-1.3.3/src/portals/Screenshot.cpp:94:61: error: call of overloaded ‘Struct(std::tuple<double, double, double>)’ is ambiguous
/usr/include/sdbus-c++/Types.h:123:18: note: candidate: ‘Struct(const std::tuple<_Ts ...>&)-> sdbus::Struct<_ValueTypes> [with _ValueTypes = {double, double, double}]’
  123 |         explicit Struct(const std::tuple<_ValueTypes...>& t)
      |                  ^~~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/tuple:1970:5: note: candidate: ‘std::Struct(_Ts ...)-> sdbus::Struct<_ValueTypes ...> [with _ValueTypes = {tuple<double, double, double>}]’
 1970 |     tuple(_UTypes...) -> tuple<_UTypes...>;
      |     ^~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/stl_pair.h:92:11: note: candidate: ‘Struct(std::tuple<_Ts ...>)-> sdbus::Struct<_ValueTypes ...> [with _ValueTypes = {double, double, double}]’
   92 |     class tuple;
      |           ^~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/tuple:993:17: note: candidate: ‘Struct(const std::tuple<_Ts ...>&)-> sdbus::Struct<_ValueTypes ...> [with _ValueTypes = {double, double, double}]’
  993 |       constexpr tuple(const tuple&) = default;
      |                 ^~~~~
/usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/tuple:995:17: note: candidate: ‘Struct(std::tuple<_Ts ...>&&)-> sdbus::Struct<_ValueTypes ...> [with _ValueTypes = {double, double, double}]’
  995 |       constexpr tuple(tuple&&) = default;
      |                 ^~~~~
/usr/include/sdbus-c++/Types.h:143:5: note: candidate: ‘sdbus::Struct(_Elements ...)-> Struct<_ValueTypes ...> [with _Elements = {std::tuple<double, double, double>}]’
  143 |     Struct(_Elements...) -> Struct<_Elements...>;
      |     ^~~~~~
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-address-of-temporary’ may have been intended to silence earlier diagnostics
ninja: build stopped: subcommand failed.
 * ERROR: gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2::guru failed (compile phase):
 *   ninja -v -j13 -l15 failed
 * 
 * Call stack:
 *     ebuild.sh, line  136:  Called src_compile
 *   environment, line 2132:  Called cmake_src_compile
 *   environment, line  865:  Called cmake_build
 *   environment, line  832:  Called eninja
 *   environment, line 1314:  Called die
 * The specific snippet of code:
 *       "$@" || die -n "${*} failed"
 * 
 * If you need support, post the output of `emerge --info '=gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2::guru'`,
 * the complete build log and the output of `emerge -pqv '=gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2::guru'`.
 * The complete build log is located at '/var/tmp/portage/gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2/temp/environment'.
 * Working directory: '/var/tmp/portage/gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2/work/xdg-desktop-portal-hyprland-1.3.3_build'
 * S: '/var/tmp/portage/gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2/work/xdg-desktop-portal-hyprland-1.3.3'

>>> Failed to emerge gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2, Log file:

>>>  '/var/tmp/portage/gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2/temp/build.log'

 * Messages for package gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2:

 * ERROR: gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2::guru failed (compile phase):
 *   ninja -v -j12 -l13 failed
 * 
 * Call stack:
 *     ebuild.sh, line  136:  Called src_compile
 *   environment, line 2132:  Called cmake_src_compile
 *   environment, line  865:  Called cmake_build
 *   environment, line  832:  Called eninja
 *   environment, line 1314:  Called die
 * The specific snippet of code:
 *       "$@" || die -n "${*} failed"
 * 
 * If you need support, post the output of `emerge --info '=gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2::guru'`,
 * the complete build log and the output of `emerge -pqv '=gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2::guru'`.
 * The complete build log is located at '/var/tmp/portage/gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2/temp/environment'.
 * Working directory: '/var/tmp/portage/gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2/work/xdg-desktop-portal-hyprland-1.3.3_build'
 * S: '/var/tmp/portage/gui-libs/xdg-desktop-portal-hyprland-1.3.3-r2/work/xdg-desktop-portal-hyprland-1.3.3'

**Comment by vaxerski** [comment]
this has been fixed, update

**Comment by Gotchfutchian** [comment]
I have a fully up to date system (as of October 6th, 11:50 AM CST 2024) and I am also having this emerge error. {Could this be because I cant update `dev-libs/boost` as that has specific requirements for like 7 other programs? Wouldnt make sense however, I would imagine it being in the dependencies if so}.

**Comment by EssenSea** [comment]
> I have a fully up to date system (as of October 6th, 11:50 AM CST 2024) and I am also having this emerge error. {Could this be because I cant update `dev-libs/boost` as that has specific requirements for like 7 other programs? Wouldnt make sense however, I would imagine it being in the dependencies if so}.

xdg-desktop-portal-hyprland in guru repos is out of date, and it is dependent on hyprwayland-scanner(also out of date in guru) ( I've not use 9999 version). Try to git clone and build from source of these two, and you may wanna follow  the README.

**Comment by Gotchfutchian** [comment]
Ah, that would explain it. Thanks for the reply.
