### ISSUE TITLE
[ERROR] - dbus: failed to connect to user bus: No such file or directory

### ISSUE THREAD

**Issue by fahimscirex** [hyprwm/xdg-desktop-portal-hyprland#27]
Telegram, Waybar, Firefox taking too much time to open, they works fine when I remove `xdg-desktop-portal`. I'm on Artix runit, so systemd isn't involved anywhere.

```
➜  ~ /usr/lib/xdg-desktop-portal-hyprland
2023/02/24 16:41:23 [ERROR] - dbus: failed to connect to user bus: No such file or directory
```

```
## ~/.config/hypr/hyprland.conf
...
exec-once = ~/.config/hypr/scripts/xdg-desktop-portal
exec-once = dbus-update-activation-environment --all
exec-once = ~/.config/hypr/scripts/gtktheme
...
```
```
## ~/.bash_profile
...
if [[ -z $WAYLAND_DISPLAY && $(tty) = "/dev/tty1" ]]; then
        eval $(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
        export SSH_AUTH_SOCK
        exec dbus-launch Hyprland >/dev/null 2>&1
fi
...
```

**Comment by vaxerski** [comment]
`exec dbus-launch Hyprland >/dev/null 2>&1`

what if you don't `dbus-launch`?

**Comment by fahimscirex** [comment]
> `exec dbus-launch Hyprland >/dev/null 2>&1`
> 
> what if you don't `dbus-launch`?

same result

**Comment by vaxerski** [comment]
well generally this looks like an issue with your dbus, not xdph / xdp

**Comment by vaxerski** [comment]
No clue. I just use sysd like a normal human being lol

**Comment by xrtxn** [comment]
I use artix openrc and it works fine

**Comment by erikeah** [comment]
@fahimscirex Try on your init script to set `dbus-launch Hyprland`, I proudly enjoy Artix Openrc and Greetd and it works. ;)

**Comment by bmariuszb** [comment]
I also use Artix(runit) I did just dbus-lauch Hyprland, then opened kitty and executed 
```
/usr/lib/xdg-desktop-portal-hyprland
```
The output
```
2023/06/18 18:56:36 [ERROR] - pipewire: couldn't connect to context
2023/06/18 18:56:36 [ERROR] - xdpw: failed to initialize screencast
'impl->enter_count > 0' failed at ../pipewire/spa/plugins/support/loop.c:349 loop_leave()
```

**Comment by erikeah** [comment]
xdg-desktop-portal-hyprland should be automatically started; dbus-launch Hyprland from your desktop manager / greeter (SDDM, greetd, GDM...) almost every one uses desktop files to describe desktop options, or in case of greetd use a predefined option.

Also, take in mind that you will need to start pipewire and wireplumber at startup, use exec-once from hyprland config file.

**Comment by vaxerski** [comment]
closing due to the v1.0 rewrite
