### ISSUE TITLE
screencast IPC not called on gpu-screen-recorder

### ISSUE THREAD

**Issue by littleblack111** [hyprwm/xdg-desktop-portal-hyprland#271]
```socat - "UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" | while read -r line; do echo "$line"; done```

executing wf-recorder will show screencast sth from the prev command

but gpu-screen-recorder doesn't seem to be affected... it doesn't output anything as if nothing happend, but screen is still being recorded

i have xdg-desktop-portal-gtk, xdg-desktop-portal-wlr and xdph

**Comment by dec05eba** [comment]
gpu screen recorder doesn't use the screencast protocol when recording a monitor, it bypasses the wayland compositor with root access. The exception to this is when using the desktop portal capture option (-w portal) in gpu screen recorder.

**Comment by littleblack111** [comment]
what does it use and where can i see its starting to record?

**Comment by dec05eba** [comment]
It accesses the linux drm (direct rendering manager) api directly, you cant see that its recording except by checking if the process is running (for example by running `pidof gpu-screen-recorder`).

**Comment by littleblack111** [comment]
i see... does this mean the waybar privacy module is useless for screencasting. since the program can just do that...

but alright, i see. not a xdph issue

**Comment by dec05eba** [comment]
Programs can only do that with root access. So in those cases yeah.

**Comment by littleblack111** [comment]
> Programs can only do that with root access. So in those cases yeah.

wdym? I did not ran gpu-screen-recorder as root? they have a kernel module or what?

**Comment by dec05eba** [comment]
> > Programs can only do that with root access. So in those cases yeah.
> 
> wdym? I did not ran gpu-screen-recorder as root? they have a kernel module or what?

it depends on how you have installed gpu screen recorder. If you use the flatpak then it will show a password prompt once. If you installed it from source or from aur then a binary called gsr-kms-server will be installed with admin capability (using setcap). This removes the need to type root password everytime you want to record. This is a small binary that one does that one thing, accesses the screen framebuffer.

**Comment by littleblack111** [comment]
oh i see. i installed from pacman.

does gsr-kms-server give the screen framebuffer to all program who asked or just gpu-screen-recorder

**Comment by dec05eba** [comment]
To all programs, just like the hyprland screencast protocol. I may consider restricting it to system installed programs. If you dont want that you have to install gpu screen recorder from source with the -Dcapabilities=false option.

**Comment by littleblack111** [comment]
nah. that would be too complicated. can you elaborate on restricting it to system installed programs? i mean that kinda just helps everyone bypass the "root access only" limit

**Comment by dec05eba** [comment]
By system installed programs it would mean any program that has been installed with root access (to /usr/bin on arch, as opposed to a binary in the users home directory). There is no reliable way to guarantee that only gpu screen recorder runs gsr-kms-server since you could just replace the gpu-screen-recorder program in /usr/bin, so might as well allow all /usr/bin programs to run it.

**Comment by littleblack111** [comment]
how would u restrict it to only programs in /usr/bin?

also I don't think its very viable to just rename gpu-screen-recorder in /usr/bin as u would need root to do so. And if your already root, why even bother doing that...

**Comment by dec05eba** [comment]
> also I don't think its very viable to just rename gpu-screen-recorder in /usr/bin as u would need root to do so. And if your already root, why even bother doing that...

thats the point, you need root to install programs in /usr/bin as well.

> how would u restrict it to only programs in /usr/bin?
linux has functionality to get the process id of the remote peer in a unix socket. From this you can check which program tried to use gsr-kms-server.

But anyways, this discussion doesn't belong here.
