### ISSUE TITLE
Huge cursor size in share picker

### ISSUE THREAD

**Issue by matthewsia98** [hyprwm/xdg-desktop-portal-hyprland#28]
![image](https://user-images.githubusercontent.com/71731492/221488391-b5e03dd0-00d6-458c-992a-9a37ed9a7335.png)
![image](https://user-images.githubusercontent.com/71731492/221488609-f93e5ca5-21d6-41c2-b272-861ae29398f5.png)

```
xdg-desktop-portal 1.16.0-1
xdg-desktop-portal-hyprland-git r250.b03b1c2-1
xdg-desktop-portal-wlr 0.6.0-1
hyprland-git r2312.4ec034a-1
```

**Comment by vaxerski** [comment]
try exporting `XCURSOR_SIZE` in your wrapper

**Comment by matthewsia98** [comment]
Thanks, that solved half of my issues.
Other half was caused by setting a scaling factor here `monitor=eDP-1,1920x1080,auto,1.25`.
Seems to work fine if I change that to `monitor=eDP-1,1920x1080,auto,1.0`.

**Comment by vaxerski** [comment]
huh, odd
