### ISSUE TITLE
remove MainPicker window

### ISSUE THREAD

**Issue by fewlesss** [hyprwm/xdg-desktop-portal-hyprland#300]
Hello, I was wondering if it's possible to remove the "MainPicker" window that pops up on OBS Startup. For example by setting a default screen option or something alike? I've tried to look into this myself but I haven't had any luck.

**Comment by vaxerski** [comment]
no, allow a restore token and it will remember

**Comment by fewlesss** [comment]
How would i do that?

**Comment by fewlesss** [comment]
Wait nevermind, ignore that
