### ISSUE TITLE
[Feature Request] Allow 3rd party share pickers

### ISSUE THREAD

**Issue by JohnOberhauser** [hyprwm/xdg-desktop-portal-hyprland#303]
I would like to be able to create my own share picker with ags.  

It seems like the share picker is pretty well isolated, and the portal just calls the `hyprland-share-picker` and listens to stdout, so third party pickers seem doable.  Ideally, there would be a new field in `xdph.conf` where the user can define a path to a script/executable.  And that script is expected to output the proper selection info like
`[SELECTION]/screen:DP-1`

**Comment by vaxerski** [comment]
sure

**Comment by JohnOberhauser** [comment]
Awesome!  Thanks!
