### ISSUE TITLE
Dependencie  xdg-desktop-portal-hyprland -git is  flagged out of date in the AUR.

### ISSUE THREAD

**Issue by RedBlizard** [hyprwm/xdg-desktop-portal-hyprland#36]
Hi ,

xdg-desktop-portal-hyprland is flagged out of date in the aur.
Just want to let you know, and it is still not possible to upgrade the dependencie.

**Comment by RedBlizard** [comment]
this can also be closed !

**Comment by ThatOneCalculator** [comment]
@vaxerski i dont have perms to close
