### ISSUE TITLE
AUR: need to update pkgrel

### ISSUE THREAD

**Issue by coffebar** [hyprwm/xdg-desktop-portal-hyprland#37]
When updating packages from yay, i get xdg-desktop-portal-hyprland-git update every time.

```
Package (1)                      Old Version     New Version     Net Change

xdg-desktop-portal-hyprland-git  r261.e1f145d-1  r261.e1f145d-1    0.00 MiB

Total Installed Size:  0.36 MiB
Net Upgrade Size:      0.00 MiB
```

You need to inc pkgrel to break this loop. Thanks.

**Comment by vaxerski** [comment]
@ThatOneCalculator

**Comment by ThatOneCalculator** [comment]
Just did AGAIN. ISTG if that doesnt solve it, it's the AUR's issue

**Comment by coffebar** [comment]
I see. The problem is not solved.
Something is wrong with pkgver.
I reviewed PKGBUILD and found `pkgver=r261.ge1f145d`.
Not sure how this oneliner works:
```
pkgver() {
  cd "$_pkgname"
  ( set -o pipefail
    git describe --long 2>/dev/null | sed 's/\([^-]*-g\)/r\1/;s/-/./g' ||
    printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
  )
}
```
but if I clone repo and run this, it will print `r261.e1f145d`
Maybe `pkgver=r261.ge1f145d` shoud be changed to  `pkgver=r261.e1f145d` and pkgrel to 4?
I could be wrong, because I don't quite understand how it worked before

**Comment by ThatOneCalculator** [comment]
I still get `r261.ge1f145d` :thinking:

**Comment by ThatOneCalculator** [comment]
Epoch'd it.

**Comment by RedBlizard** [comment]
Just did the update with paru that worked yay could not do the update.

**Comment by coffebar** [comment]
For me, it was updated successfully with yay!

```
Package (1)                      Old Version     New Version       Net Change
xdg-desktop-portal-hyprland-git  r261.e1f145d-1  1:r261.e1f145d-4   -0.01 MiB
```

**Comment by RedBlizard** [comment]
yeah its fixed no issues anymore !!
