### ISSUE TITLE
Enhancement: video bridge

### ISSUE THREAD

**Issue by EysseW** [hyprwm/xdg-desktop-portal-hyprland#39]
Maybe you could patch https://invent.kde.org/davidedmundson/xwaylandvideobridge to work on hyprland and implement it :D

Don't really know what else to add, really. Would be great because it would allow us to stream wayland apps off of xwayland apps.

**Comment by vaxerski** [comment]
What does not work about it?

**Comment by EysseW** [comment]
It crashes as soon as you actually try to screenshare the window, [reports say the same thing about both swaywm and newm](https://invent.kde.org/davidedmundson/xwaylandvideobridge/-/issues/2), seems to be a wlroots issue, but the devs haven't showed themselves in the project since release.

**Comment by vaxerski** [comment]
How the fuck do you get this thing to even run, I installed xwaylandvideobridge-bin from the aur, launched the pwbypass script and it aint doing shit

**Comment by vaxerski** [comment]
fixed in 803c00db1191604d50766358dbc5be2de4fcb4e7

it flashes a bit for me, but cba to properly implement this shit. IDEK why this was chosen as a method in the first place.

**Comment by EysseW** [comment]
Cool, thanks!

**Comment by KrolixW** [comment]
Seems like it was reverted by 510257c

**Comment by vaxerski** [comment]
lol oops 0527deefe8f8124928bdd3cbe0b289925227ded7
