### ISSUE TITLE
Screenshare freezes after a few seconds

### ISSUE THREAD

**Issue by midiidev** [hyprwm/xdg-desktop-portal-hyprland#40]
I don't know where the issue is exactly, but when I screenshare, it works for a few seconds, then will freeze until I restart the screenshare. Running xdph with `-lTRACE`, it doesn't appear to log any errors when the screenshare freezes.

**Comment by vaxerski** [comment]
what hyprland ver? IIRC this was introduced a couple days ago and patched also a couple days ago

**Comment by midiidev** [comment]
I just updated and no longer have the issue. I need to remember to update my system more often

**Comment by vaxerski** [comment]
lmao
