### ISSUE TITLE
Error while building

### ISSUE THREAD

**Issue by vaderkos** [hyprwm/xdg-desktop-portal-hyprland#41]
Hi, I've encountered an error during install through yay.

`protocols/meson.build:26.1: ERROR : File //usr/share/protocols/hyprland-global-shortcuts-v1.xml do3s not exist.`

**Comment by vaxerski** [comment]
@fufexan I asked you to fix this >:(

**Comment by vaxerski** [comment]
fixed with 03f252d9271889484293614d39f9cf6bf6a91c54
