### ISSUE TITLE
Upright screens are handled wrong

### ISSUE THREAD

**Issue by galister** [hyprwm/xdg-desktop-portal-hyprland#43]
There are a couple of discrepancies when attempting to cast upright screens with XDPH (and possibly 180 / flipped as well).

On KDE, OBS (PipeWire) on a screen with `transform: 1` gives an upright image that's already rotated, with dimensions correct for upright presentation. I would think this is the correct behavior, since screen sharing is one of the primary use-cases for this, where the user can't easily rotate or flip their screen.

On Hyprland with XDPH, OBS (PW) shows an image that's lying flat (not rotated) with parts of the image being black, and other parts missing, seemingly due to a wrong offset. The dimensions are the native dimensions of the screen without any adjustment. [Image Link.](https://media.discordapp.net/attachments/1065335880975388782/1094939121253879881/image.png?width=825&height=611)

Behavior is the same with both memfd and dmabuf capture.

Comparing to wlr_export_dmabuf (wlrobs), with that we get the native image unrotated, but there's no offset issue and the image is perfectly usable after manually rotating inside OBS.

**Comment by vaxerski** [comment]
closing due to the v1.0 rewrite

**Comment by gual** [comment]
@vaxerski, this is my issue as well. Do you have any pointers on how to approach this? When sharing, if there is a rotation for a monitor, the shared image does not get rotated. I'm using v1.3.2. Should I create another ticket?

**Comment by Arnau478** [comment]
Related: #228
