### ISSUE TITLE
Interesting Discord Screenshare Problem

### ISSUE THREAD

**Issue by emrakyz** [hyprwm/xdg-desktop-portal-hyprland#49]
**Background:**
1-) I have the latest git versions of **xdg-desktop-portal**,  **xdg-desktop-portal-hyprland**, grim, slurp, pipewire, wireplumber and **hyprland**.
2-) I have made sure that I don't have other implementations installed.
3-) I start the script as recommended and checked with "`pidof -s xdg-desktop-portal`" and "`pidof -s xdg-desktop-portal-hyprland`"
4-) I can take screenshots with Grim and Slurp without a problem.
5-) I can record a video that has sounds with wf-recorder, ffmpeg without a problem.
6-) I use Chromium browser for Discord since I can't run the Discord app even with ozone flags. It segfaults. Other types of Discords (such as Webcord or GTKCord) are also same.

**Problem:**
1-) I can share a Chromium tab without a problem.
2-) I can also share any window from the window tab.
3-) I can't share the "screen". The output is black screen.
      * I can share the screen by selecting the "Region" on the "Window" tab. But it doesn't work for the first time. It's always black at first. Then, I need to constantly try and somehow, I select the region (I basically select the whole screen with my mouse) and it works.

**Comment by vaxerski** [comment]
you're running chromium in xwayland, so that's expected. You need to run it in native wayland to be able to screenshare.
