### ISSUE TITLE
Chrome 112 shares a black screen

### ISSUE THREAD

**Issue by kschat** [hyprwm/xdg-desktop-portal-hyprland#50]
When sharing my screen on Chrome 112.0.5615.165, only a black screen is shown. The Chrome logs are flooded with

```
[4958:7102:0420/093242.251780:ERROR:egl_dmabuf.cc(569)] Failed to record frame: Error creating EGLImage - EGL_BAD_ALLOC
[4958:7102:0420/093242.251805:ERROR:shared_screencast_stream.cc(791)] Dropping DMA-BUF modifier: 144115188622392067 and trying to renegotiate stream parameters
```

[This same issue](https://github.com/emersion/xdg-desktop-portal-wlr/issues/266) was reported in `xdg-desktop-portal-wlr`, and it's fixed in 0.7 (I have tested myself).

**Comment by vaxerski** [comment]
so it was here jesus christ use the search bar #45

**Comment by kschat** [comment]
I did search. Nothing came up for the error I was seeing in Chrome. Looking at #45, you claim that the latest `-git` version fixes it. That's what I'm using, and I'm still seeing the issue.

```
 —— pikaur -Qs xdg-desktop-portal-hyprland
local/xdg-desktop-portal-hyprland-git 1:r261.e1f145d-4
    xdg-desktop-portal backend for hyprland
```

**Comment by vaxerski** [comment]
![image](https://user-images.githubusercontent.com/43317083/233497807-f8efac7b-9cfb-41ac-b6a6-23b5f0337eb1.png)
![image](https://user-images.githubusercontent.com/43317083/233497813-af932cf3-2ab1-404b-b1aa-a090547f6378.png)

very git

**Comment by kschat** [comment]
I guess it's my fault for assuming the `-git` AUR package would actually track `master` 

<img width="641" alt="Screenshot 2023-04-20 at 6 32 07 PM" src="https://user-images.githubusercontent.com/929018/233500929-dfc6d361-da8a-4662-a1a9-95a0e4cd7fa2.png">

**Comment by vaxerski** [comment]
it does, you just need to manually update it, like any -git package. -git packages do not get updates.

**Comment by kschat** [comment]
`pikaur` handles this for you, but it looks like I turned it off and forgot to turn it back on. My mistake. Thanks for being a rubber duck.
