### ISSUE TITLE
Update xdpw

### ISSUE THREAD

**Issue by Teddy-Kun** [hyprwm/xdg-desktop-portal-hyprland#51]
As mentioned in #29 screensharing does not work on RDNA3 cards, due to a bug in xdpw. This was fixed in the latest xdpw and I would ask you to update xdph to resolve this issue here as well.

**Comment by vaxerski** [comment]
I am unsure what is _not_ up-to-date with xdpw. Are you on the latest release, 0.3?

**Comment by Teddy-Kun** [comment]
I rebuild xdph and now it works, I think makepkg did not realize that just the submodule changed. Closing the issue
