### ISSUE TITLE
Huge cursor in some apps - related to monitor scale.

### ISSUE THREAD

**Issue by mapleroyal** [hyprwm/xdg-desktop-portal-hyprland#57]
On my high res monitor, I need 2x scale for things to not be extremely tiny.
`monitor=eDP-1,3840x2400@59.993999,0x0,2`

But for some apps the cursor is HUGE unless I use 1x scale—and therefore half resolution which makes everything blurry.
`monitor=eDP-1,1920x1200@59.993999,0x0,1`

I notice this issue in CopyQ and Edge.

**Comment by mapleroyal** [comment]
To clarify, this issue is when the app's _are_ using wayland mode.

**Comment by vaxerski** [comment]
that should be an issue with the app itself. Try exporting XCURSOR_SIZE with the `env` keyword in your config to 24 (or whatever cursor size you use)
