### ISSUE TITLE
Cursor erratically jumps around when running Final Fantasy 14

### ISSUE THREAD

**Issue by vhalragnarok** [hyprwm/xdg-desktop-portal-hyprland#59]
Summary of the Bug:

When playing FInal Fantasy using Hyprland with XDG-Desktop-Portal-Hyprland cursor will erratically and randomly move around (frequently happens in combination with Right Click, but I have observed the behavior without pushing right click). This issue is not present in KDE'S Implementation of Wayland (KWin), nor is it present when using Hyprland with the XDG-Desktop-Portal-Wlr

Steps to Reproduce the Bug:

Play Final Fantasy like normal. Try to move the camera and obverse erratic behavior / observe the position of the cursor when idle. I am not sure if this happens in other games. This bug is also present when  using Gamescope which uses the Dekstop Portal present (but only depends on WLRoots). I have tested this with several mice and several implementations of the XDG-Desktop-Portal, and this issue only occurs with the Hyprland fork. 

Expected Behavior:

Cursor moves where directed by mouse input. 

Relevant System Information:

Arch Linux, 3440x1440 Monitor, AMD Ryzen R9 5950X, AMD 7900XTX GPU (can provide other specs as needed). Tested with: Logitech, Corsiar, and Steelseries mice to isolate mouse problem but all produced the same behavior. 

Workaround:

Use XDG-Desktop-Portal-Wlr

Priority to fix:
Low. I don't know how or why this is attached to this, but here we are. XDG-Dekstop-Portal-Wlr works if you don't need Global Hotkeys.

**Comment by vaxerski** [comment]
I fail to see how xdph could cause this
