### ISSUE TITLE
Firefox screensharing fails

### ISSUE THREAD

**Issue by AFriemann** [hyprwm/xdg-desktop-portal-hyprland#6]
Hey,

tried this with firefox and google meet just now and it doesn't seem to work.

I get a popup for screen/window/location selection but the screensharing just sort of "blocks" and nothing happens. Ran the small script in the Usage section to get some actual output and saw this error:

```
2022/12/13 19:38:33 [ERROR] - wlroots: no output / window found
```

that's the only output I managed to get, if you have any idea how to get something more useful I'd be happy to try!

**Comment by vaxerski** [comment]
yeah you're supposed to choose something from the popup. What do you choose? does output or window work?

**Comment by AFriemann** [comment]
of course I am choosing something :) I tried with both a window and a monitor, same result on both. I'll try to run it with debug logs enabled later today!

**Comment by AFriemann** [comment]
here is the log output

```
2022/12/23 15:27:02 [INFO] - dbus: create session method invoked
2022/12/23 15:27:02 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_38/webrtc989803445
2022/12/23 15:27:02 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_38/webrtc_session726073532
2022/12/23 15:27:02 [INFO] - dbus: app_id:
2022/12/23 15:27:02 [INFO] - dbus: select sources method invoked
2022/12/23 15:27:02 [INFO] - dbus: request_handle: /org/freedesktop/portal/desktop/request/1_38/webrtc1767289102
2022/12/23 15:27:02 [INFO] - dbus: session_handle: /org/freedesktop/portal/desktop/session/1_38/webrtc_session726073532
2022/12/23 15:27:02 [INFO] - dbus: app_id:
2022/12/23 15:27:02 [INFO] - dbus: option types:3
2022/12/23 15:27:02 [INFO] - dbus: option multiple: 0
2022/12/23 15:27:02 [INFO] - dbus: option cursor_mode:2
2022/12/23 15:27:02 [DEBUG] - dbus: select sources: found matching session /org/freedesktop/portal/desktop/session/1_38/webrtc_session726073532
2022/12/23 15:27:02 [INFO] - wlroots: capturable output: AU Optronics model: 0x2036: id: 43 name: eDP-1
2022/12/23 15:27:02 [INFO] - wlroots: capturable output: Microstep model: MSI MAG322CQR: id: 44 name: DP-1
2022/12/23 15:27:02 [DEBUG] - Screencast: Picker: Running command "WAYLAND_DISPLAY=wayland-0 QT_QPA_PLATFORM="wayland" XCURSOR_SIZE=24 HYPRLAND_INSTANCE_SIGNATURE=49063f949df92ab60244ff9e08025172bc512a8d_1670955845 XDPH_WINDOW_SHARING_LIST="1683466368[HC	]firefox-nightly[HT	]Nightly — Sharing Indicator[HE	]1682677872[HC	]firefox-nightly[HT	]Meet – dqm-usqj-bhi — Firefox Nightly[HE	]1682677536[HC	]firefox-nightly[HT	]Firefox screensharing fails · Issue #6 · hyprwm/xdg-desktop-portal-hyprland — Firefox Nightly[HE	]1682677200[HC	]Alacritty[HT	]bash:/home/******[HE	]1682676864[HC	]Slack[HT	]Threads - ****** - 13 new items - Slack[HE	]1682676528[HC	]Alacritty[HT	]bash:/home/******[HE	]1682667808[HC	]Alacritty[HT	]bash:/home/******[HE	]" hyprland-share-picker"
2022/12/23 15:27:08 [DEBUG] - Screencast: Window sharing attempted but the toplevel protocol is not implemented by the compositor!
2022/12/23 15:27:08 [ERROR] - wlroots: no output / window found
2022/12/23 15:27:08 [INFO] - dbus: session closed
2022/12/23 15:27:08 [DEBUG] - dbus: destroying session 0x558964568800
```

looking at the error message, is it the wlroots version? `community/wlroots 0.15.1-6`

i'll try to upgrade that in a moment. Hyprland itself should be a pretty recent build but I'll also see if I can pull in the latest

```
yay -Ss hyprland | grep -i installed
aur/xdg-desktop-portal-hyprland-git r224.3d3c5a4-2 (+2 1.83) (Installed: r246.9fb4fae-1)
aur/waybar-hyprland-git 0.9.16.r12.gd2b4076a-1 (+7 2.45) (Installed: 0.9.16.r22.g94d6ae97-1)
aur/hyprland-git r2042.ga7ed3a5-1 (+14 2.91) (Installed: r2109.49063f9-1)
```

**Comment by vaxerski** [comment]
> Screencast: Window sharing attempted but the toplevel protocol is not implemented by the compositor!

old hyprland

**Comment by AFriemann** [comment]
I seee.. is it possible that `yay` gets confused by the version scheme? `r2109` seems higher than `r2042`. I just assumed the "Installed" version was newer because `yay -Syu` didn't include it.

Any recommendation on how to stay updated there?

**Comment by vaxerski** [comment]
yay cannot fetch updates for -git packages. `yay -S hyprland-git` and select cleanbuild.

**Comment by AFriemann** [comment]
I see. Wonder if there's sth like smart-live-rebuild for arch.. sorry, I wasn't aware of that :) I seem to have another issue now but I'll try to make sure everything is up to date now and will get in touch if I can't figure it out myself. Thanks for the support!

**Comment by AFriemann** [comment]
It works! :D I thought I'd never see it happen. Thanks again!
