### ISSUE TITLE
xdg-desktop-portal-hyprland dependency problem

### ISSUE THREAD

**Issue by l0py2** [hyprwm/xdg-desktop-portal-hyprland#63]
Both xdg-desktop-portal-hyprland and xdg-desktop-portal-hyprland-git depend on xdg-desktop-portal. So when installing the XDG desktop implementation the AUR helper or Pacman package manager asks for one XDG desktop portal implementation which can conflict with the XDG desktop portal Hyprland implementation.

**Comment by vaxerski** [comment]
isnt that an issue on the packagers side?
