### ISSUE TITLE
`org.freedesktop.impl.portal.Screenshot`'s `PickColor` does't work as expected

### ISSUE THREAD

**Issue by zefr0x** [hyprwm/xdg-desktop-portal-hyprland#66]
When I request a color using the [`PickColor`](https://github.com/flatpak/xdg-desktop-portal/blob/b4f298b0b472433710853c218fdc656f942e00d9/data/org.freedesktop.impl.portal.Screenshot.xml#L107) method in the `org.freedesktop.impl.portal.Screenshot` interface, I will see a white semi-transparent layer in my whole screen (like when using the `Screenshot` method).

Most times I will get a white color `#EEEEEE` as a response to my request, but sometimes I will get a real color.

After some random tests it seems to behave like this:
- When requesting a color then point in somewhere and click on the screen, I will get the white color.
- If I made the request and then directly move the cursor very fast and click while I'm moving the cursor, I will get the color that I clicked on.

---

I expect it to behave like: 
- https://github.com/hyprwm/hyprpicker `Freezes your displays when picking the color`
- https://github.com/jgmdev/wl-color-picker `Don't freezes` `Better`

Also a `hyprpicker` like UI would be a very great thing.

**Comment by vaxerski** [comment]
not possible to fix at the moment
