### ISSUE TITLE
Some buttons in Steam that open file browser dont work after new steam update.

### ISSUE THREAD

**Issue by bakicelebi** [hyprwm/xdg-desktop-portal-hyprland#67]
https://github.com/ValveSoftware/steam-for-linux/issues/9447

Seems like after the new UI update steam is using xdp for opening file browser and it is not working with xdph.

**Comment by xadips** [comment]
Was this resolved somehow as I'm still having this issue?

**Comment by darman96** [comment]
having this issue as well

**Comment by vaxerski** [comment]
xdph doesn't implement fileChooser, so it's not to be reported here. xdg-desktop-portal-gtk does implement one and is a useful addon.

**Comment by darman96** [comment]
Could you document this on the wiki?
Especially since the hyprland-desktop-portal section hints that multiple portals are not supported and may cause problems.

**Comment by vaxerski** [comment]
![image](https://github.com/hyprwm/xdg-desktop-portal-hyprland/assets/43317083/eb053945-b75a-4c4d-b5ec-cb57aad0ecbc)
?

**Comment by darman96** [comment]
Oh, didn't see that. But I would include xdg-desktop-portal-gtk as a must have since -hyprland doesn't offer a fileChooser.
