### ISSUE TITLE
Screen recording flickers when sharing screen

### ISSUE THREAD

**Issue by NomisIV** [hyprwm/xdg-desktop-portal-hyprland#73]
When I share my screen, the recorded screen flickers erratically.
This only affects the recorded or shared screen, not my actual screen.
I have no idea what could cause this, but I've tried looking everywhere, and not found anything helpful.
The issue persists between my desktop and my laptop (both AMD CPU and GPU systems)
I'm running NixOS 23.11 and "bleeding edge" Hyperland at commit `9fc5f4c48b20875337b7a1eddd274f191edd504d`), but this has been an issue for a long time.

Example:

https://github.com/hyprwm/xdg-desktop-portal-hyprland/assets/47303199/7be15350-ace8-41da-aa08-b55cc9e8856c

Let me know if (or what) more information you would like, or if I'm asking in the wrong repo.
Thanks! :)

**Comment by vaxerski** [comment]
bleeding edge my ass
![image](https://github.com/hyprwm/xdg-desktop-portal-hyprland/assets/43317083/a0e650a3-2912-406e-8323-c7592003275c)

this was fixed in https://github.com/hyprwm/Hyprland/commit/a9b8e2159c2813a6951d0b0186fbb7f2f8554d3e
