### ISSUE TITLE
Firefox screen sharing only works with entire monitor, not region or window

### ISSUE THREAD

**Issue by fazo96** [hyprwm/xdg-desktop-portal-hyprland#74]
I am running NixOS unstable. On stable 23.05, this worked perfectly. Eventually I switched to unstable and it stopped working.

I am running Hyprland with firefox-wayland and I tried sharing both wayland windows and xwayland ones and it doesn't work. Doesn't work with region either, however full screen works.

I really appreciated the region feature especially because my screen is really big and it was useful to share a portion where I could put a couple window tiles.

**Comment by vaxerski** [comment]
region sharing is broken as of rn, but window share should work. @fufexan for nix.

**Comment by fazo96** [comment]
I upgraded and tried again today

Sharing full screen: works perfectly
Sharing window: google meet never starts showing the screen share and its screen share button remains disabled, requiring a hard refresh
Sharing region: the screen share appears but it's fully black

I am hoping I can get either region or window to work

**Comment by fufexan** [comment]
This has been fixed in Hyprland. If you use the flake package, please update. If you use Hyprland from Nixpkgs, you will have to wait for https://github.com/NixOS/nixpkgs/pull/247008 to be merged.
