### ISSUE TITLE
Screenshare picker showing twice on ozone

### ISSUE THREAD

**Issue by Mikilio** [hyprwm/xdg-desktop-portal-hyprland#80]
This probably isn't an issue from here but I'd like to get confirmation before I move to blame chromium.

Everytime I screen share using ozone platform be it a chromium browser or electron I need to select my target twice.

This is a mild annoyance

**Comment by vaxerski** [comment]
since OBS does it correctly, that sounds like a chromium issue. Firefox in some cases asks thrice as well.

**Comment by Mikilio** [comment]
I will leave this open for when someone finds a workaround just for the sake of discoverabilty

**Comment by vaxerski** [comment]
dupe of #11
