### ISSUE TITLE
Since 1.0 share picker doesn't work

### ISSUE THREAD

**Issue by ferrreo** [hyprwm/xdg-desktop-portal-hyprland#83]
With the 1.0 share picker I just get this in my portal logs after selecting something (all 3 tabs have the same result):

wlroots: no output / window

If I revert just the share picker to the previous build it works fine even with the 1.0 portal etc.

I get this using browsers, OBS, anything really.

Any tips on how I could debug this to help you get to the bottom of the issue?

**Comment by vaxerski** [comment]
oh, dang. I forgot to attach the picker to the release bin lol.

`wlroots: no output / window`
This is an error from before 1.0. You have updated the picker, but not xdph.

**Comment by ferrreo** [comment]
@vaxerski  the systemd service file in the updated tar is wrong too it is pointing to /usr/libexec instead of /usr/lib (like the makefile does). Also makefile could do with installing that service too

**Comment by vaxerski** [comment]
feel free to make a MR, I suck at these
