### ISSUE TITLE
Slow loading gtk apps and waybar at least  30 seconds or more

### ISSUE THREAD

**Issue by RedBlizard** [hyprwm/xdg-desktop-portal-hyprland#90]
Hi , since yesterday waybar and other gtk apps started to load very slow.
Removing the xdg-desktop-portal-hyprland solved the issue the same problem is also with the rest of the xdg-desktop-portals, this needs to patched or fixed.

**Comment by vaxerski** [comment]
this indicates xdp / xdph is crashing, or your dbus is broken. That's an issue on your side, unfortunately.

**Comment by NgoHuy** [comment]
`[CRITICAL] Couldn't create the dbus connection ([org.freedesktop.DBus.Error.AccessDenied] Failed to request bus name `
the bug is belong to xdg-desktop-portal-hyprland not other. Seem to the connection to dbus is denied.

**Comment by vaxerski** [comment]
usually means it's already running or dbus is dead

**Comment by NgoHuy** [comment]
Firstly, all others xdg are running. Secondly, no xdgh is running. 
If the bug is belong to dbus, why is only xgdh affected?
