### ISSUE TITLE
Detect missing qt5/6-wayland

### ISSUE THREAD

**Issue by ItsDrike** [hyprwm/xdg-desktop-portal-hyprland#91]
This is a feature request about an issue described in #82. Currently, the portal will hard crash if qt5-wayland or qt6-wayland is not installed, without much helpful information anywhere in the logs on what's going on.

It would be nice if the portal was able to inform you about this missing dependency instead, preventing a lot of potential confusion. Even just making the crash contain a message about a missing dependency would be fine, though ideally, it'd be great if the portal opened a graphical window informing you that this dependency isn't installed.

A GUI window would be better since many people might still not realize where to even look for this. All that the user might see is that clicking on "select window" or similar buttons that should spawn the portal window picker actually won't do anything. However I'm not sure if a window like this would be easily achievable, considering that the window itself might need to use qt to actually be rendered. Perhaps a hyprland notification can be used instead? Or at least a regular xdg notification, though this might not be ideal for people who don't have a notification daemon installed.

**Comment by vaxerski** [comment]
why didnt this shit auto close

**Comment by vaxerski** [comment]
AW FUCK WRONG BRANCH AAAAAAAAA
