### ISSUE TITLE
constant CPU usage

### ISSUE THREAD

**Issue by primalmotion** [hyprwm/xdg-desktop-portal-hyprland#94]
xdg-desktop-portal-hyprland  is now continously using ~5/6% of CPU, even with nothing running else on hyprland. Restarting it does not change anything

**Comment by vaxerski** [comment]
yeah, it changed methodology. I'll try to optimize the event loop.

**Comment by vaxerski** [comment]
should be improved with 2f48e655037411a81669ac8f84dd90bcb6c0c00f

let me know

**Comment by primalmotion** [comment]
works like a charm. back to 0.0% most of the time. Thanks!

**Comment by HexPandaa** [comment]
I just updated to the latest version and after a reboot xdg-desktop-portal-hyprland is constantly using 120% CPU and draining the battery.
I'll try not to restart to help you debug the problem.

**Comment by mrvruj** [comment]
Same here, seeing constant 5-6% CPU usage by xdg-desktop-portal using hyprland-git package from AUR. Nothing else running, just empty workspaces.

**Comment by vaxerski** [comment]
@HexPandaa #103
@mrvruj probably outdated

**Comment by The-Maize** [comment]
Constantly an issue in Tuxedo OS (Ubuntu based)  have to manually kill it to stop it from using cpu cycles.

**Comment by tacosrdelicioso** [comment]
same. Using hyprland-git version as well.  It started doing it right after I logged out this time. all of a sudden I heard my fans kick on so I checked btop. I just killed it

**Comment by vaxerski** [comment]
this one was fixed in 1.2.0/1.2.1 and is a dupe of some other issue I cba to find rn

**Comment by horror-proton** [comment]
https://github.com/hyprwm/xdg-desktop-portal-hyprland/blob/2f48e655037411a81669ac8f84dd90bcb6c0c00f/src/core/PortalManager.cpp#L321-L326
Wait, did you mean `pollfds[i].revents` here? @vaxerski

**Comment by vaxerski** [comment]
oops

**Comment by vaxerski** [comment]
fixed d8daa2a84f5e9b38eb89e0631b294e7d0a83aa9b

**Comment by arvind2109** [comment]
I'm new to Linux and Hyprland, can someone explain how to fix this issue.
